name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/**'
      - 'syntax/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
      - 'syntax/**'
jobs:
  lint:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.x"
    name: deno lint
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.version }}
      - name: run lint
        run: deno lint --ignore=denops/gh/github/graphql/
  test:
    strategy:
      matrix:
        runner:
          #- windows-latest
          - macos-latest
          - ubuntu-latest
        version:
          - "1.x"
        host_version:
          - vim: "v9.0.0472"
            nvim: "v0.8.0"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v3
        with:
          path: "./repo"
      - uses: actions/checkout@v3
        with:
          repository: "vim-denops/denops.vim"
          path: "./denops.vim"
      - uses: denoland/setup-deno@main
        with:
          deno-version: "${{ matrix.version }}"
      - uses: thinca/action-setup-vim@v1
        id: vim
        with:
          vim_type: "Vim"
          vim_version: "${{ matrix.host_version.vim }}"
          download: "never"
      - name: Check Vim
        run: |
          echo ${DENOPS_TEST_VIM_EXECUTABLE}
        env:
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.vim.outputs.executable_path }}
      - uses: thinca/action-setup-vim@v1
        id: nvim
        with:
          vim_type: "Neovim"
          vim_version: "${{ matrix.host_version.nvim }}"
      - name: Check Neovim
        run: |
          echo ${DENOPS_TEST_NVIM_EXECUTABLE}
        env:
          DENOPS_TEST_NVIM_EXECUTABLE: ${{ steps.nvim.outputs.executable_path }}
      - name: Test
        run: |
          mkdir -p $HOME/.config/gh
          cat <<EOF > $HOME/.config/gh/hosts.yml
          github.com:
            oauth_token: "xxxxx"
            user: skanehira
          EOF
          make test
        env:
          DENOPS_TEST_DENOPS_PATH: "../denops.vim"
          DENOPS_TEST_VIM_EXECUTABLE: ${{ steps.vim.outputs.executable_path }}
          DENOPS_TEST_NVIM_EXECUTABLE: ${{ steps.nvim.outputs.executable_path }}
          TWIHI_TEST_ENDPOINT: http://localhost:8080 
        timeout-minutes: 5
        working-directory: ./repo
