#!/bin/bash


source shlib.sh

usage()
{
    cat <<-END
usage: git-history-compact <date>

    Remove commits before <date>;
    Do not support history with more than one parent.
END
}

main()
{
    local dt="${1-30 day}"

    if [ "$dt" = "-h" ]; then
        usage
        exit 0
    fi

    dd About to compact commit before "$dt"

    commit=$(git log -n1 --before="$dt" --format="%h")

    if [ "$commit" = "" ]; then
        info No commit before "$dt". Do not need to compact.
        exit 0
    fi

    # create a new commit without parent, with the same content(tree) with "$commit"
    tree="$(git_tree_hash $commit)"
    new_commit=$(git_commit_copy $commit $tree "")

    git rebase --onto $new_commit $commit 
}

main "$@"
