#!/bin/sh

source shlib.sh

if test -z "$1" || test "-h" = "$1" || test "--help" = "$1"
then
    name=${0##*/}
    echo "$name <branch>|<rev-list>..." >&2
    exit 0
fi

remotemode=0
while test -n "$1"
do
    case $1 in
        -r)
            remotemode=1
            shift
            ;;
        *)
            break
            ;;
    esac
done

base=
if test "$remotemode" = "1"
then
    if test -z "$1"
    then
        branchname=$(git_head_branch)
        die_empty "$branchname" "head is not on a branch"
    else
        branchname="$1"
        shift
    fi

    remote=$(git_branch_default_remote $branchname)
    die_empty "$remote" "find remote of branch $branchname"

    upstream=$(git_branch_default_upstream $branchname)
    die_empty "$upstream" "find upstream of branch $branchname"

    base=$remote/$branchname
fi

sedscript="'"'/^$/,$d'"'"
GIT_EDITOR='f(){ cat $1 | sed '$sedscript'; }; f' git rebase --interactive --autosquash $base "$@"
