#!/bin/sh

PATH=$PATH:$(git --exec-path)
. git-sh-setup

source _git_xp_lib.sh

dd "git dir: $GIT_DIR"

# cat <<-END
# dir:    "dir/path"
# remote: origin  git://github.com/jquery/jquery-tmpl.git
# remote: bkp     git://github.com/jquery/jquery-tmpl.git
# head:   origin  master
# END

init()
{
    working_dir="$(git_working_root)"
    die_empty "$working_dir" no git working dir found

    conf_fn="$working_dir/.gitrepo"
    test -r "$conf_fn" \
        || die "$conf_fn" is unreadable
}

doit()
{
    local k=
    local a1=
    local a2=

    local dirpath=
    local remote=
    local url=
    local tip=
    local repo_path=

    local state=nil

    { cat "$conf_fn"; echo ""; } | while read k a1 a2; do

        case "$k" in
            '')
                if test -z "$dirpath"; then
                    dd "no conf read, continue"
                    continue
                fi
                repo_path="$working_dir/$dirpath"

                if test -d "$repo_path"; then
                fi

                # dirpath=
                # remote=
                # url=
                # tip=
                ;;

            dir:)
                dirpath="$a1"
                dd "find dir: $dirpath"
                ;;

            remote:)
                remote="$a1"
                url="$a2"
                dd "remote: $remote : $url"
                ;;
            head:)
                head="$a1"
                dd "head: $head"
                ;;
        esac
    done

    dd "finished"
}

main()
{
    init
    doit
}


main "$@"
