#!/bin/sh

source shlib.sh

main()
{
    local cmd="${1-update}"

    case "$cmd" in
        -h|--help)
            usage
            exit 0
        ;;
    esac

    local root=$(git_working_root)
    [ "x$root" = "x" ] && die 'looking for git repo root'
    cd "$root"

    local conf_fn=./.gitupstream

    while read name url; do

        git remote add "$name" "$url"
        git remote set-url "$name" "$url"
        git fetch -p "$name"

    done<"$conf_fn"
}

usage()
{
    cat <<-END
usage: git upstream

    Manage upstream git repos.
    It depends on a configure file ".gitupstream" at git repo root dir.

    Install:
    Copy this script to a dir in PATH.

    Configure file ".gitupstream" syntax:

        <upstream_name_1>     <upstream_url_1>
        <upstream_name_2>     <upstream_url_2>
        ...

    Example:
        > cat .gitupstream
        chriswolfvision     git@github.com:chriswolfvision/eplot.git


    With above config, "git upstream" will:

        -   Add missing remote.
        -   Try to set-url for each upstream.
        -   fetch -p the upstream repo.

END
}

main "$@"
