#!/bin/sh

g=git-2.16.3
package=$g.tar.xz

cd ~
mkdir tmpgit
cd tmpgit
wget http://kernel.org/pub/software/scm/git/$package -O $package
tar -xzf $package
cd git-*

if [ -f /etc/centos-release ]; then

    yum -y groupinstall "Development Tools"
    yum -y install    \
        gettext-devel \
        openssl-devel \
        perl-CPAN     \
        perl-devel    \
        zlib-devel    \

    make configure
    ./configure --prefix=$HOME
    make install

else
    # for msgfmt
    apt-get install gettext

    make prefix=$HOME/local NO_TCLTK=YesPlease install
fi
