#!/bin/sh

# for msgfmt
which -s apt-get \
    && apt-get install gettext


yum install -y              \
    curl-devel              \
    expat-devel             \
    gcc                     \
    gettext-devel           \
    libcurl-devel           \
    openssl-devel           \
    perl-ExtUtils-MakeMaker \
    zlib-devel              \

cd ~

g=git-2.11.0
package=$g.tar.xz
wget http://kernel.org/pub/software/scm/git/$package

tar -xf $package

cd $g
make prefix=$HOME/local NO_TCLTK=YesPlease install

# ./configure --prefix=$HOME && make install
