# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

edition = "2018"

# binop_separator = "Front"
# comment_width = 80
# condense_wildcard_suffixes = true
# control_brace_style = "ClosingNextLine"
# enum_discrim_align_threshold = 60
# fn_args_layout = "Tall"
# force_multiline_blocks = true
# format_code_in_doc_comments = true
# format_macro_bodies = true
# format_macro_matchers = true
# max_width = 120
#
# merge_imports = true
# reorder_imports = true
# imports_layout = "Vertical"
#
# newline_style = "Unix"
# normalize_comments = true
# struct_field_align_threshold = 60
# trailing_comma = "Always"
# use_try_shorthand = true
# wrap_comments = true

# match_block_trailing_comma = true

# ignore = [
#     "src/types.rs",
#     "src/foo/bar.rs",
# ]
