#!/bin/bash


base="${BASH_SOURCE[0]}";
while [ -h "$base" ]; do base=`readlink "${base}"`; done
base="$( cd -P "$( dirname "$base" )" && pwd )"

cd ~
. ~/xp/bash-d/git.inst

git remote add coding git@git.coding.net:drmingdrmer/homefolder.git
