#!/bin/sh

# do not init if it is not a ternimal
[ -t 1 ] || return 0

# make "," a ", "
bind '",":", "'

# git help log:
# --diff-filter:
# include:
#   ACDMRTUXB
# exclude:
#   acdmrtuxb
#
# Added                            (A),
# Copied                           (C),
# Deleted                          (D),
# Modified                         (M),
# Renamed                          (R),
#
# have their type i.e. regular file, symlink, submodule, ...
# changed                          (T),
# are Unmerged                     (U),
# are Unknown                      (X),
# or have had their pairing Broken (B)
export git_comma_options='a   all
b   simplify-by-decoration
c   cached
d   date-order
fA  diff-filter=A
fB  diff-filter=B
fC  diff-filter=C
fD  diff-filter=D
fM  diff-filter=M
fR  diff-filter=R
fT  diff-filter=T
fU  diff-filter=U
fX  diff-filter=X
fa  diff-filter=a
fb  diff-filter=b
fc  diff-filter=c
fd  diff-filter=d
fm  diff-filter=m
fr  diff-filter=r
ft  diff-filter=t
fu  diff-filter=u
fx  diff-filter=x
fp  first-parent
g   graph
i   ignore-all-space
ld  format=diff
lf  format=fuller
lm  format=medium
lo  format=oneline
lr  format=pullrequest
n   name-only
oM  no-merges
om  merges
p   patch
r   relative
R   reverse
t   stat
W   word-diff=color
w   color-words=[[:alpha:]]+|[^[:space:]]'

git_comma_make_option_expr()
{
    # output is a concatenated variable string,
    # such as: '"$opt_all$opt_simplify_by_decoration..."'

    local vars=""
    local prev_option_name=
    while read shortcut option; do

        option_name=$(echo "${option%%=*}" | tr "-" "_")

        if [ "$option_name" = "$prev_option_name" ]; then
            continue
        fi

        opt_cc='$opt_'$option_name
        vars="${vars}${opt_cc}"
        prev_option_name="$option_name"

    done <<<"$git_comma_options"
    echo "\"$vars\""
}

export git_comma_option_expr="$(git_comma_make_option_expr)"

fmt_hash='%C(dim yellow)%h%C(reset)'
fmt_time='%C(bold cyan)%ar%C(reset)'
fmt_subject='%C(bold green)%s%C(reset)'
fmt_author='%C(yellow)%an%C(reset)'
fmt_ref='%C(dim yellow)%d%C(reset)'
fmt_body='%C(white)%+b%C(reset)'

# git_comma_format_for_diff="format:'%<(8)$fmt_hash%<(8,trunc)$fmt_author %<(7,trunc)$fmt_time $fmt_subject $fmt_ref%>(1,ltrunc)%b$fmt_body'"
# git_comma_format_for_diff="format:'$fmt_subject - $fmt_author $fmt_time $fmt_hash$fmt_ref%>(1,ltrunc)%b$fmt_body'"
# git_comma_format_for_diff="format:'$fmt_hash $fmt_subject - $fmt_author $fmt_time $fmt_ref%>(1,ltrunc)%b$fmt_body'"
export git_comma_format_for_diff="format:'$fmt_hash %C(bold green)%s%C(reset) - $fmt_author $fmt_time %C(bold red)% D%C(reset) %>(1,ltrunc)%b$fmt_body'"
