aliases:
    # list repos: `gh repos cli`
    repos: |
        !gh api --paginate graphql -f owner="$1" -f query='
          query($owner: String!, $per_page: Int = 100, $endCursor: String) {
            repositoryOwner(login: $owner) {
              repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
                nodes { nameWithOwner }
                pageInfo { hasNextPage endCursor }
              }
            }
          }
          ' | jq -r '.data.repositoryOwner.repositories.nodes[].nameWithOwner' | sort

    reposall: |
        !gh api --paginate graphql -f owner="$1" -f query='
          query($owner: String!, $per_page: Int = 100, $endCursor: String) {
            repositoryOwner(login: $owner) {
              repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
                nodes {
                  name
                  nameWithOwner
                  description
                  stargazerCount
                  primaryLanguage {
                    name
                  }
                  repositoryTopics(first:5) {
                    edges {
                      node {
                        topic {
                          name
                        }
                      }
                    }
                  }
                }
                pageInfo { hasNextPage endCursor }
              }
            }
          }
          ' | jq -r '[.data.repositoryOwner.repositories.nodes[] | {
            name: .nameWithOwner,
            desc: .description,
            lang: .primaryLanguage.name,
            tags: [.repositoryTopics.edges[].node.topic.name],
            }]' |  filter-gh-repos.py
