aliases:
    # get parent of a forked parent
    # `gh repo_parent <owner> <repo_name>`
    repo_parent: |
        !gh api graphql -f owner="$1" -f repo="$2" -f query='
          query($owner: String!, $repo: String!) {
            repositoryOwner(login: $owner) {
              repository(name: $repo) {
                parent {
                    owner {
                        login
                    }
                    name
                }
              }
            }
          }
          '\
          | jq --join-output -r '.data.repositoryOwner.repository.parent.owner.login+"/"+.data.repositoryOwner.repository.parent.name'
    # list repos: `gh repos cli`
    repos: |
        !gh api --paginate graphql -f owner="$1" -f query='
          query($owner: String!, $per_page: Int = 100, $endCursor: String) {
            repositoryOwner(login: $owner) {
              repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
                nodes { nameWithOwner }
                pageInfo { hasNextPage endCursor }
              }
            }
          }
          ' | jq -r '.data.repositoryOwner.repositories.nodes[].nameWithOwner' | sort
    reposNameUrlDesc: |
        !gh api --paginate graphql -f owner="$1" -f query='
          query($owner: String!, $per_page: Int = 100, $endCursor: String) {
            repositoryOwner(login: $owner) {
              repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
                nodes {
                  name
                  url
                  description
                }
                pageInfo { hasNextPage endCursor }
              }
            }
          }
          '
    reposall: |
        !gh api --paginate graphql -f owner="$1" -f query='
          query($owner: String!, $per_page: Int = 100, $endCursor: String) {
            repositoryOwner(login: $owner) {
              repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
                nodes {
                  name
                  nameWithOwner
                  description
                  stargazerCount
                  primaryLanguage {
                    name
                  }
                  repositoryTopics(first:5) {
                    edges {
                      node {
                        topic {
                          name
                        }
                      }
                    }
                  }
                }
                pageInfo { hasNextPage endCursor }
              }
            }
          }
          ' | jq -r '[.data.repositoryOwner.repositories.nodes[] | {
            name: .nameWithOwner,
            desc: .description,
            lang: .primaryLanguage.name,
            tags: [.repositoryTopics.edges[].node.topic.name],
            }]' |  filter-gh-repos.py
    im: issue list --label A-meta
    il: issue list
    iw: issue view --web
version: "1"
