#!/bin/sh

cmd=${1:-clone}

while read name gist_id; do
    echo === repo: $name cmd: $cmd ===
    if [ -d "$name" ]; then
        case $cmd in
            push)
                ( cd $name && git push origin master; )
                ;;
            fetch)
                ( cd $name && git fetch origin; )
                ;;
            pull)
                ( cd $name && git pull --ff-only origin; )
                ;;
            status)
                ( cd $name && git status; )
                ;;
            commit)
                (
                cd $name && git add -u || exit 1
                { git diff-index --name-only HEAD -- | grep -qs .; } && git commit -m 'auto commit' || exit 0
                    )
                ;;
            clone)
                ;;
            *)
                ( cd $name && git "$@"; )
                ;;

        esac
    else
        case $cmd in
            clone)
                (
                url=git@github.com:baishancloud/$name.git
                mkdir -p $name \
                    && cd $name \
                    && git init \
                    && git remote add origin $url \
                    && git fetch \
                    && git checkout master
                )

                ;;
        esac
    fi
done <<-END
git-subrepo
git-upstream
END
