#!/bin/sh

cmd=${1:-clone}

while read name gist_id; do
    echo === $name ===
    if [ -d "$name" ]; then
        case $cmd in
            push)
                ( cd $name && git push origin master; )
                ;;
            fetch)
                ( cd $name && git fetch origin; )
                ;;
            pull)
                ( cd $name && git pull --ff-only origin; )
                ;;
            status)
                ( cd $name && git status; )
                ;;
            commit)
                (
                cd $name && git add -u || exit 1
                { git diff-index --name-only HEAD -- | grep -qs .; } && git commit -m 'auto commit' || exit 0
                    )
                ;;
            clone)
                ;;
            *)
                ( cd $name && git "$@"; )
                ;;

        esac
    else
        case $cmd in
            clone)
                git clone git@gist.github.com:$gist_id.git $name
                ;;
        esac
    fi
done <<-END
git-box                 07faee6c4f7c8e31da3c5210cfa04034
git-gotofix             241dd1b3655f04190b0c6d06aa1dd258
git-subrepo             ff72ee00df7b7a359263fc3b15d093b0
END
