set      nocompatible
filetype plugin indent on
syntax   on


let g:deoplete#enable_at_startup=1

let g:deoplete#sources#clang#libclang_path = "/Library/Developer/CommandLineTools/usr/lib/libclang.dylib"
let g:deoplete#sources#clang#clang_header = "/Library/Developer/CommandLineTools/usr/lib/clang/11.0.3"


" venv base
let vbase = substitute(expand("<sfile>"), 'vimrc', '', '')
let vbase = substitute(vbase, '\V\[/\\]\$', '', '')

" remove traditional vim runtime path
set rtp-=$HOME/.vim
set rtp-=$HOME/.vim/after

let plugins = [
      \ 'xptemplate',
      \ 'deoplete-clang',
      \ 'deoplete.nvim',
      \ ]

for plg in plugins
    let &rtp .= ',' . vbase . '/rtp/' . plg
endfor


