# admin
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/admin.1
# using Deroffing man parser
complete -c admin -o 'y\\*<comment\\*>' --description 'OPTopt -C id set or remove the changeset file string in the 1.'
complete -c admin -s D --description 'remove the delta changeset marks (rarely used--… [See Man Page]'
complete -c admin -s h --description 'check s. file structure in general, but limited to  features.'
complete -c admin -o hh --description 'as above, but also check  specific (in addition to ) features.'
complete -c admin -o hhh --description 'as above, but also check time stamps.  read initial text from.'
complete -c admin -s q --description 'run quietly.  make .'
complete -c admin -s i --description '.'
complete -c admin -s z --description 'recalculate file checksum.  compress stored s. file with .'

