# annotate
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/annotate.1
# using Deroffing man parser
complete -c annotate -s k --description 'do not expand RCS or SCCS keywords.  This option is implied by.'

