# ansible-vault
# Autogenerated from man page /usr/local/share/man/man1/ansible-vault.1
# using Deroffing man parser
complete -c ansible-vault -l vault-password-file --description '.'
complete -c ansible-vault -l new-vault-password-file --description '.'
complete -c ansible-vault -s h -l help --description '.'

