# ansible-galaxy
# Autogenerated from man page /usr/local/share/man/man1/ansible-galaxy.1
# using Deroffing man parser
complete -c ansible-galaxy -s h -l help --description '.'
complete -c ansible-galaxy -s r --description '.'
complete -c ansible-galaxy -s f -l force --description '.'
complete -c ansible-galaxy -s i -l ignore-errors --description '.'
complete -c ansible-galaxy -s n -l no-deps --description '.'
complete -c ansible-galaxy -s p -l roles-path --description '.'
complete -c ansible-galaxy -l role-file --description '.'
complete -c ansible-galaxy -l init-path --description '.'
complete -c ansible-galaxy -l offline --description '.'
complete -c ansible-galaxy -l galaxy-tags --description '.'
complete -c ansible-galaxy -l platforms --description '.'
complete -c ansible-galaxy -l author --description '.'
complete -c ansible-galaxy -s c -l ignore-certs --description '.'
complete -c ansible-galaxy -s s -l server --description '.'
complete -c ansible-galaxy -l github-token --description '.'
complete -c ansible-galaxy -l branch --description '.'
complete -c ansible-galaxy -l list --description '.'
complete -c ansible-galaxy -l remove --description '.'

