# assetutil
# Autogenerated from man page /usr/share/man/man1/assetutil.1
# using Darwin man parser
complete -c assetutil -s V --description 'version information for assetutil.'
complete -c assetutil -s I --description 'Produce a JSON description of the asset catalog… [See Man Page]'
complete -c assetutil -s i --description 'Keep all assets that have idiom that is given o… [See Man Page]'
complete -c assetutil -s s --description 'Keep all assets that have scale factor that is … [See Man Page]'
complete -c assetutil -s M --description 'Keep all assets that have memory class that is … [See Man Page]'
complete -c assetutil -s g --description 'Keep all assets that have graphics class that i… [See Man Page]'
complete -c assetutil -s h --description 'process the hosted idioms list, this is a list … [See Man Page]'
complete -c assetutil -s t --description 'Subtype to keep integer IT Fl c Main Assets.'
complete -c assetutil -s o --description 'Output file name, if no output file is given th… [See Man Page]'

