# attach
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/attach.1
# using Deroffing man parser
complete -c attach -s C --description 'Do not commit the component to the product.'
complete -c attach -s q --description 'Run quietly.  Clone the repository up to and including cset .'

