# bam
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bam.1
# using Deroffing man parser
complete -c bam -s a --description 'option the local BAM server is ignored, so all … [See Man Page]'

