# bisect
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bisect.1
# using Deroffing man parser
complete -c bisect -l cmd --description 'LOPTreq --cmd prog  <prog> is a program (usuall… [See Man Page]'
complete -c bisect -l dir --description 'below) and the test program will be run at the … [See Man Page]'
complete -c bisect -l keys --description 'Print MD5KEYS instead of dates as the prefix to… [See Man Page]'

