# bk-alias
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-alias.1
# using Deroffing man parser
complete -c bk-alias -s C --description 'Normally, modifying the aliases database result… [See Man Page]'
complete -c bk-alias -s h --description '(here) Used when showing aliases; causes only a… [See Man Page]'
complete -c bk-alias -s k --description '(keys) Used when showing aliases; causes indivi… [See Man Page]'
complete -c bk-alias -s m --description '(missing) Used when showing aliases; causes onl… [See Man Page]'
complete -c bk-alias -s v --description 'Used when showing aliases; causes aliases to be… [See Man Page]'

