# bk-abort
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-abort.1
# using Deroffing man parser
complete -c bk-abort -s f --description 'Do not prompt for confirmation, just do it. if \\n[NESTED] \\{\\.'
complete -c bk-abort -s S --description 'In a nested repository, limit the abort to this component.'

