# bk-base64
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-base64.1
# using Deroffing man parser
complete -c bk-base64 -s d --description 'option is passed then the encoding is unpacked … [See Man Page]'

