# bk-collapse
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-collapse.1
# using Deroffing man parser
complete -c bk-collapse -s l --description 'option to bk collapse saves a list of the md5ke… [See Man Page]'
complete -c bk-collapse -s e --description 'Leave the resulting changes as locked, modified… [See Man Page]'
complete -c bk-collapse -s S --description '.'
complete -c bk-collapse -l standalone --description 'Just collapse the current component.'
complete -c bk-collapse -l no-save --description 'when fixing the entire changeset the normal beh… [See Man Page]'
complete -c bk-collapse -s q --description 'suppress most messages EXAMPLES Fix a problem i… [See Man Page]'

