# bk-comments
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-comments.1
# using Deroffing man parser
complete -c bk-comments -s p --description 'Generate the list of all comments in the files … [See Man Page]'

