# bk-co
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-co.1
# using Deroffing man parser
complete -c bk-co -o 'A\\*<bdnpru\\*>' --description 'OPTreq -A bdnpru Align prefix output in a human readable form.'
complete -c bk-co -s g --description 'Suppress the retrieval of any text; sometimes useful with.'
complete -c bk-co -s h --description 'Invert sense of file\'s hash flag.  Include revs in .'
complete -c bk-co -s k --description 'Don\'t expand RCS or SCCS keywords.'
complete -c bk-co -s l --description 'Checkout the file for editing (same as bk edit ).'
complete -c bk-co -s p --description 'Write file to standard output (useful in scripts).'
complete -c bk-co -s P --description 'Write to stdout, forcing a check out even if th… [See Man Page]'
complete -c bk-co -s q --description 'Run quietly, suppressing diagnostics.'
complete -c bk-co -s S --description 'Check out the file if and only if it is not alr… [See Man Page]'
complete -c bk-co -s T --description 'Set the gfile\'s modification time to the delta\'s creation time.'

