# bk-cset
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-cset.1
# using Deroffing man parser
complete -c bk-cset -s C --description 'Clear and remark all changeset boundaries in al… [See Man Page]'
complete -c bk-cset -s q --description 'Run quietly.'
complete -c bk-cset -s S --description 'If using -i or -x and not currently in the prod… [See Man Page]'

