# bk-csettool
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-csettool.1
# using Deroffing man parser
complete -c bk-csettool -s S --description '.'
complete -c bk-csettool -l standalone --description 'By default, bk csettool runs in the product of … [See Man Page]'
complete -c bk-csettool -o 'f\\fIGiven' --description 'csettool starts up with the specified file and … [See Man Page]'

