# bk-clone
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-clone.1
# using Deroffing man parser
complete -c bk-clone -s s --description 'option.   If.'
complete -c bk-clone -l checkout --description 'Valid values for.'
complete -c bk-clone -l downgrade --description 'By default, new clones will use the same storag… [See Man Page]'
complete -c bk-clone -l identical --description 'When cloning a product, have the set of populat… [See Man Page]'
complete -c bk-clone -l no-hardlinks --description 'Clone nomally uses hard links whenever it can.'
complete -c bk-clone -l parents --description 'Instead of setting the parent to the .'
complete -c bk-clone -s q --description 'Run quietly.  Clone the repository up to and including cset .'
complete -c bk-clone -o sTHERE --description 'can be use to make the destination of the clone… [See Man Page]'
complete -c bk-clone -l upgrade --description 'By default, new clones will use the same storag… [See Man Page]'

