# bk-csets
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-csets.1
# using Deroffing man parser
complete -c bk-csets -s D --description 'Use  bk difftool (gui mode) or bk diffs -pu (te… [See Man Page]'
complete -c bk-csets -l stats --description 'Print a statistics header like diffstat.'
complete -c bk-csets -s T --description 'Use  bk changes to display the changesets (text mode).'
complete -c bk-csets -s v --description 'Pass.'

