# bk-config
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-config.1
# using Deroffing man parser
complete -c bk-config -s v --description 'Displays the location of all config key-value p… [See Man Page]'

