# bk-clean
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-clean.1
# using Deroffing man parser
complete -c bk-clean -s p --description 'Prints diffs for all modified files.'
complete -c bk-clean -s q --description 'Run quietly.'
complete -c bk-clean -s v --description 'Run verbosely.  SEE ALSO CATEGORY Common.'

