# bk-config-etc
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-config-etc.1
# using Deroffing man parser
complete -c bk-config-etc -s s --description 'option is not used, then the.'

