# bk-crypto
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-crypto.1
# using Deroffing man parser
complete -c bk-crypto -s i --description 'Create a new RSA key pair.'
complete -c bk-crypto -s s --description 'Create a RSA signature for data read from stdin… [See Man Page]'
complete -c bk-crypto -s v --description 'Validate a RSA signature using a public key.'

