# bk-ci
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-ci.1
# using Deroffing man parser
complete -c bk-ci -s a --description 'Normally,  bk ci is used to modify existing files.'
complete -c bk-ci -s c --description 'Take checkin comments from  SCCS/c.  filename.'
complete -c bk-ci -s f --description 'Force the creation of a null delta even if ther… [See Man Page]'
complete -c bk-ci -s l --description 'Follow check in with a locked check out like Se… [See Man Page]'
complete -c bk-ci -s p --description 'Print differences before prompting for comments.'
complete -c bk-ci -s q --description 'Run silently.'
complete -c bk-ci -s u --description 'Follow check in with an unlocked check out.'

