# bk-diffs
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-diffs.1
# using Deroffing man parser
complete -c bk-diffs -o stats-only --description 'OPTreq -A bdpru Align prefix output in a human readable form.'
complete -c bk-diffs -s b --description 'Ignore changes in amount of white space.'
complete -c bk-diffs -s B --description 'Ignore  changes  that  just  insert or delete blank lines.'
complete -c bk-diffs -s c --description 'Do old-style context diffs.'
complete -c bk-diffs -s f --description 'Normally, bk diffs does not bother to diff agai… [See Man Page]'
complete -c bk-diffs -s F --description 'Only useful in unified diffs, the given regex w… [See Man Page]'
complete -c bk-diffs -s h --description 'Don\'t print headers.'
complete -c bk-diffs -s H --description 'Prefix diffs with the checkin comments of that … [See Man Page]'
complete -c bk-diffs -s n --description 'Do RCS style diffs.'
complete -c bk-diffs -l normal --description 'Instead of unified diffs (the default) print le… [See Man Page]'
complete -c bk-diffs -s N --description 'If a specified file is not under revision contr… [See Man Page]'
complete -c bk-diffs -s p --description 'Procedural diffs, like Diff revision .'
complete -c bk-diffs -s s --description 'Display side-by-side diffs.'
complete -c bk-diffs -l stats --description 'Print a statistics header like diffstat in addi… [See Man Page]'
complete -c bk-diffs -l stats-only --description 'Print a statistics header like diffstat and sup… [See Man Page]'
complete -c bk-diffs -s S --description '.'
complete -c bk-diffs -l standalone --description 'Use with -L in a nested component when you want… [See Man Page]'
complete -c bk-diffs -s v --description 'Be verbose about non-matching ranges.'
complete -c bk-diffs -s w --description 'Ignore white space when comparing lines.'

