# bk-describe
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-describe.1
# using Deroffing man parser
complete -c bk-describe -l brief --description 'Skip the timestamp.'
complete -c bk-describe -l dirty --description 'If the tree has modified, extra, and/or pending… [See Man Page]'

