# bk-export
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-export.1
# using Deroffing man parser
complete -c bk-export -o Nur --description 'patches between any two revisions of the source tree.'
complete -c bk-export -s h --description 'Disable patch header.  Export only pathnames matching .'
complete -c bk-export -s k --description 'Do not expand keywords (default is to expand keywords).'
complete -c bk-export -s p --description 'Do procedural diffs when exporting a patch (see diff(1)).'
complete -c bk-export -s S --description '.'
complete -c bk-export -l standalone --description 'Just export the current component.'
complete -c bk-export -o sHERE --description '.'
complete -c bk-export -s T --description 'Set gfile modification time to check-in time.'
complete -c bk-export -s v --description 'Be verbose.'
complete -c bk-export -s w --description 'Make files writable (default is read-only).'

