# bk-edit
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-edit.1
# using Deroffing man parser
complete -c bk-edit -s q --description 'run quietly Edit the file, rolling it back to t… [See Man Page]'

