# bk-findmerge
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-findmerge.1
# using Deroffing man parser
complete -c bk-findmerge -s a --description 'list all of the least upper bound merges where … [See Man Page]'

