# bk-gethost
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-gethost.1
# using Deroffing man parser
complete -c bk-gethost -s n --description 'print the internet address instead of the host.'
complete -c bk-gethost -s r --description 'print the real host name, ignoring.'

