# bk-gone
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-gone.1
# using Deroffing man parser
complete -c bk-gone -s q --description 'be quiet.  NOTE.'

