# bk-getuser
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-getuser.1
# using Deroffing man parser
complete -c bk-getuser -s r --description 'print the real user name, ignoring.'

