# bk-grep
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-grep.1
# using Deroffing man parser
complete -c bk-grep -s h --description 'Do not print filenames with matches when multip… [See Man Page]'
complete -c bk-grep -s H --description 'Print the file name even if there is only one f… [See Man Page]'
complete -c bk-grep -s i --description 'Ignore case distinctions in both the pattern an… [See Man Page]'
complete -c bk-grep -s l --description 'Suppress normal output; instead print the name … [See Man Page]'
complete -c bk-grep -s L --description 'Suppress normal output; instead print the name … [See Man Page]'
complete -c bk-grep -s n --description 'Prefix each line with the line number from its input file.'
complete -c bk-grep -s q --description 'Do not produce any output.'
complete -c bk-grep -s v --description 'Invert the sense of matching, to select non-matching lines.'
complete -c bk-grep -s x --description 'Select only those matches that exactly match the whole line.'

