# bk-help
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-help.1
# using Deroffing man parser
complete -c bk-help -s a --description 'Just search the docs for the string.'
complete -c bk-help -s k --description 'Similar to.'
complete -c bk-help -s p --description 'disable the use of any pager just send the output to stdout.'

