# bk-here
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-here.1
# using Deroffing man parser
complete -c bk-here -s a --description 'option to bk here check prints out all URLs in … [See Man Page]'
complete -c bk-here -s f --description 'below for how to skip this check.'
complete -c bk-here -s q --description 'Run quietly.'
complete -c bk-here -s v --description 'When listing aliases, show alias expansions usi… [See Man Page]'

