# bk-id
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-id.1
# using Deroffing man parser
complete -c bk-id -s 5 --description 'Return package identity as an md5key.'
complete -c bk-id -s r --description 'displays the repository identity.'
complete -c bk-id -s S --description 'in a nested collection return the identity of t… [See Man Page]'

