# bk-import
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-import.1
# using Deroffing man parser
complete -c bk-import -o 'H\\*<hostname\\*>' --description '-C Do not commit the ChangeSet.'
complete -c bk-import -s C --description 'Do not commit the ChangeSet.'
complete -c bk-import -s f --description 'Force; do not prompt for list editing.'
complete -c bk-import -s F --description 'Fast; run more quickly for large imports.'
complete -c bk-import -s i --description 'Prompts for a regular expression to apply to the list of files.'
complete -c bk-import -s q --description 'Be quiet.  Add tag .'
complete -c bk-import -s v --description 'Be verbose.'
complete -c bk-import -s x --description 'Prompts for a regular expression to apply to the list of files.'
complete -c bk-import -s h --description 'turn off verification of contents (faster, less safe).'
complete -c bk-import -s T --description 'Do not import tags.  The default is to import tags.'
complete -c bk-import -s u --description 'Run files through bk undos first; this will con… [See Man Page]'
complete -c bk-import -s r --description 'Do not do rename processing when doing patch imports.'
complete -c bk-import -s R --description 'If a patch fails to apply cleanly, back out the… [See Man Page]'

