# bk-lock
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-lock.1
# using Deroffing man parser
complete -c bk-lock -s l --description 'List the lockers of a repository.'
complete -c bk-lock -s q --description 'quiet, exit status only.'
complete -c bk-lock -s r --description 'Add a read lock (non-exclusive) and sleep until interrupted.'
complete -c bk-lock -s w --description 'Add a write lock (exclusive) and sleep until interrupted.'
complete -c bk-lock -s L --description 'Wait for the repository to become locked (prima… [See Man Page]'
complete -c bk-lock -s U --description 'Wait for the repository to become unlocked (pri… [See Man Page]'

