# bk-level
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-level.1
# using Deroffing man parser
complete -c bk-level -s l --description 'Just list the level on a line by itself.   Useful for scripts.'

