# bk-log
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-log.1
# using Deroffing man parser
complete -c bk-log -o 'c2006/07.\\' --description 'OPTreq - n A numeric argument that limits the n… [See Man Page]'
complete -c bk-log -o r+ --description 'which restricts the set to the most recent revision.'
complete -c bk-log -s d --description 'but read the dspec from a file.'
complete -c bk-log -s D --description 'Do not skip files in the BitKeeper/deleted directory.'
complete -c bk-log -s f --description 'Print the changes in forward (oldest to newest) order.'
complete -c bk-log -s c --description 'or.'
complete -c bk-log -s r --description '.'
complete -c bk-log -l lattice --description 'Restrict the deltas to those on the lattice bet… [See Man Page]'
complete -c bk-log -l longest --description 'Restrict the deltas to those on the longest lin… [See Man Page]'
complete -c bk-log -s n --description 'Add a newline to each printed record.'
complete -c bk-log -s S --description '.'
complete -c bk-log -l standalone --description 'Use with -L in a nested component when you want… [See Man Page]'
complete -c bk-log -o 'r1.3..1.6' --description 'prints all deltas that are in 1. 6\'s history but are not in 1.'
complete -c bk-log -o 'c2006/07..2006' --description 'prints all deltas from July 1 2006 to Dec 31 2006.'
complete -c bk-log -o 'c2006..2006' --description 'prints all deltas from Jan 1 2006 to Dec 31 2006.'
complete -c bk-log -o 'c-1d..' --description 'prints all deltas made in the last 24 hours; si… [See Man Page]'

