# bk-mv
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-mv.1
# using Deroffing man parser
complete -c bk-mv -s f --description 'option (use of which is not recommended).'

