# bk-merge
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-merge.1
# using Deroffing man parser
complete -c bk-merge -s s --description 'Perform a set merge instead of a normal file merge.'

