# bk-portal
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-portal.1
# using Deroffing man parser
complete -c bk-portal -s q --description 'the exit status indicates portal status; 0 mean… [See Man Page]'
complete -c bk-portal -s r --description 'Unmark the current product as a portal.'

