# bk-pending
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-pending.1
# using Deroffing man parser
complete -c bk-pending -s S --description '.'
complete -c bk-pending -l standalone --description 'Limit the list to the current component.'
complete -c bk-pending -s q --description 'No output.'

