# bk-port
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-port.1
# using Deroffing man parser
complete -c bk-port -s C --description 'Do not commit the ported changeset[s] to the product.'
complete -c bk-port -s i --description 'Turn off automerge feature in resolve.'
complete -c bk-port -s q --description 'Be quiet.'
complete -c bk-port -s R --description 'Do not run resolve at all.   You must run  bk resolve  later.'
complete -c bk-port -s s --description 'Pass .'
complete -c bk-port -s T --description 'Pass .'
complete -c bk-port -s u --description 'Do not complete the port if there are local changesets, i. e.'

