# bk-partition
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-partition.1
# using Deroffing man parser
complete -c bk-partition -s k --description 'communicate with repositories that have gone th… [See Man Page]'
complete -c bk-partition -l keep-deleted --description 'Normally, partition prunes all deleted files.'
complete -c bk-partition -s q --description 'Run quietly.  EXAMPLE.'

