# bk-push
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-push.1
# using Deroffing man parser
complete -c bk-push -s a --description 'If the parent is ahead of your repository, turn… [See Man Page]'
complete -c bk-push -s q --description 'Run quietly.'
complete -c bk-push -s T --description 'Pass .'

