# bk-pull
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-pull.1
# using Deroffing man parser
complete -c bk-pull -l auto-populate --description '--auto-populate automatically populate missing … [See Man Page]'
complete -c bk-pull -l auto-port --description 'automatically turn the pull into a port if needed.'
complete -c bk-pull -l batch --description 'Pass .'
complete -c bk-pull -s i --description 'Turn off automerge feature in resolve.'
complete -c bk-pull -s q --description 'Be quiet.'
complete -c bk-pull -s R --description 'Do not run resolve at all.   You must run  bk resolve  later.'
complete -c bk-pull -l safe --description 'In a nested collection, using this option means… [See Man Page]'
complete -c bk-pull -l unsafe --description 'below.'
complete -c bk-pull -l stats --description 'After finishing the pull, print statistics abou… [See Man Page]'
complete -c bk-pull -s T --description 'Pass .'
complete -c bk-pull -s u --description 'Do not complete the pull if there are local changesets, i. e.'
complete -c bk-pull -s v --description 'Be verbose by listing each file.  SEE ALSO CATEGORY Common.'

