# bk-pwd
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-pwd.1
# using Deroffing man parser
complete -c bk-pwd -s P --description 'Print the relative path from the root of the pr… [See Man Page]'
complete -c bk-pwd -s R --description 'Print the relative path from the root of the re… [See Man Page]'
complete -c bk-pwd -s s --description 'Print the short form (aka 8. 3 form) of the path.'

