# bk-range
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-range.1
# using Deroffing man parser
complete -c bk-range -l lattice --description 'Restrict the deltas to those on the lattice bet… [See Man Page]'
complete -c bk-range -l longest --description 'Restrict the deltas to those on the longest lin… [See Man Page]'
complete -c bk-range -s q --description 'run quietly; default is to warn about all files… [See Man Page]'
complete -c bk-range -s S --description '.'
complete -c bk-range -l standalone --description 'Use with -L in a nested component when you want… [See Man Page]'

