# bk-repocheck
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-repocheck.1
# using Deroffing man parser
complete -c bk-repocheck -l check-opts -o 'e\'' --description '.'
complete -c bk-repocheck -s q --description 'Run quietly.'
complete -c bk-repocheck -s S --description 'Just check the current repo.'

