# bk-repogca
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-repogca.1
# using Deroffing man parser
complete -c bk-repogca -s d --description 'but read the dspec from a file.'
complete -c bk-repogca -s 5 --description 'A short hand for asking for a spec of ".'
complete -c bk-repogca -s k --description 'A short hand for asking for a spec of ".'
complete -c bk-repogca -s S --description 'In a component in a nested collection, produce … [See Man Page]'

