# bk-root
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-root.1
# using Deroffing man parser
complete -c bk-root -s S --description 'option.  CATEGORY Admin.'

