# bk-repotype
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-repotype.1
# using Deroffing man parser
complete -c bk-repotype -s q --description 'the exit status is 0 for all valid repositories… [See Man Page]'

