# bk-resolve
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-resolve.1
# using Deroffing man parser
complete -c bk-resolve -s a --description 'Automerge.'
complete -c bk-resolve -s A --description 'Auto advance.'
complete -c bk-resolve -s c --description 'No conflicts.'
complete -c bk-resolve -s q --description 'Be quiet.'
complete -c bk-resolve -s r --description 'Re-merge.'
complete -c bk-resolve -l batch --description 'do not do interactive resolve of any conflicts,… [See Man Page]'
complete -c bk-resolve -s T --description 'Text-only.'

