# bk-relink
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-relink.1
# using Deroffing man parser
complete -c bk-relink -s q --description 'Run quietly.'

