# bk-rmgone
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-rmgone.1
# using Deroffing man parser
complete -c bk-rmgone -s n --description 'Dry run.   Just print out the files that would be removed.'
complete -c bk-rmgone -s q --description 'Run quietly.'
complete -c bk-rmgone -s S --description '.'
complete -c bk-rmgone -l standalone --description 'In a nested collection the bk rmgone command no… [See Man Page]'

