# bk-remerge
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-remerge.1
# using Deroffing man parser
complete -c bk-remerge -s T --description 'Use a text based merge tool.  SEE ALSO CATEGORY File.'

