# bk-set
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-set.1
# using Deroffing man parser
complete -c bk-set -s k --description 'list all answers as keys, not as tags or revisions.'
complete -c bk-set -s n --description 'prefix each output line with the filename, i. e. , ChangeSet|1.'
complete -c bk-set -s t --description 'list all answers as tags where possible, else revisions.'
complete -c bk-set -o tt --description 'list only those answers which are tagged and li… [See Man Page]'
complete -c bk-set -o tr --description 'list only those answers which are tagged but li… [See Man Page]'
complete -c bk-set -o tk --description 'list only those answers which are tagged but li… [See Man Page]'
complete -c bk-set -s o --description 'The union operation, familiar to programmers as… [See Man Page]'
complete -c bk-set -s a --description 'The intersection operator, familiar to programm… [See Man Page]'
complete -c bk-set -s d --description 'The difference operator lists all members in se… [See Man Page]'
complete -c bk-set -s x --description 'The symmetric difference operator, familiar to … [See Man Page]'
complete -c bk-set -s e --description 'The element operator treats the specified revis… [See Man Page]'
complete -c bk-set -s S --description 'perform the set operation on the current component.'

