# bk-support
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-support.1
# using Deroffing man parser
complete -c bk-support -s T --description 'Use a text editor rather than the default graph… [See Man Page]'

