# bk-sfio
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-sfio.1
# using Deroffing man parser
complete -c bk-sfio -s e --description 'Echo mode.'
complete -c bk-sfio -s i --description 'Extract all files from the archive.'
complete -c bk-sfio -s m --description 'Transfer file modes (default not to do so).'
complete -c bk-sfio -s o --description 'Create an archive.'
complete -c bk-sfio -s p --description 'List contents of an archive.'
complete -c bk-sfio -s q --description 'Quiet mode, when combined with the create or ex… [See Man Page]'
complete -c bk-sfio -s f --description 'Force mode, when combined with extract, will ov… [See Man Page]'

