# bk-setup
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-setup.1
# using Deroffing man parser
complete -c bk-setup -s C --description 'When run inside a product, setup will create a component.'
complete -c bk-setup -l compat --description 'Create the package using a backwards compatible… [See Man Page]'
complete -c bk-setup -s f --description 'Don\'t ask for confirmation.'
complete -c bk-setup -s P --description 'The repository being created is a product repository, i. e.'
complete -c bk-setup -s p --description 'print the field names to stdout (used by setuptool).  EXAMPLES.'

