# bk-smerge
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-smerge.1
# using Deroffing man parser
complete -c bk-smerge -o '	assert(sc->tree);' --description '.'
complete -c bk-smerge -o '	sc' --description '+	sc = sccs_init(file, INIT_NOCKSUM|INIT_SAVEPR… [See Man Page]'
complete -c bk-smerge -s 2 --description 'Enable the 2 way output format (like diff3 (1)).'
complete -c bk-smerge -s g --description 'Enable \'gca\' output format that shows the local… [See Man Page]'
complete -c bk-smerge -s n --description 'Enable the \'newonly\' output format.   (like.'
complete -c bk-smerge -s e --description 'Print examples of all 4 output formats from  bk smerge .'
complete -c bk-smerge -s f --description 'Enable fdiff output.   (Used internally by .'
complete -c bk-smerge -s h --description 'Display automerge algorithms by number that are… [See Man Page]'

