# bk-sccslog
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-sccslog.1
# using Deroffing man parser
complete -c bk-sccslog -o 'c1992/07.\\' --description '-b Show basenames instead of full pathnames. tp .'
complete -c bk-sccslog -s b --description 'Show basenames instead of full pathnames.  Cut off dates.'
complete -c bk-sccslog -s D --description 'Factor out duplicate comments and print the results as.'
complete -c bk-sccslog -s d --description 'but read the dspec from a file.'
complete -c bk-sccslog -s f --description 'Print the changes in forwards order (oldest to newest).'
complete -c bk-sccslog -s c --description '.'
complete -c bk-sccslog -s C --description 'or.'
complete -c bk-sccslog -s r --description '.'
complete -c bk-sccslog -s n --description 'Add  a newline to each printed record (sometime… [See Man Page]'
complete -c bk-sccslog -s S --description '.'
complete -c bk-sccslog -l standalone --description 'Use with -L in a nested component when you want… [See Man Page]'
complete -c bk-sccslog -o r+ --description 'prints the most recent delta.'
complete -c bk-sccslog -o 'r1.3..1.6' --description 'prints all deltas that are in 1. 6\'s history, but are not in 1.'
complete -c bk-sccslog -o 'c1992/07..1992' --description 'prints all deltas from July 1 \'92 to Dec 31 \'92.'
complete -c bk-sccslog -o 'c1992..1992' --description 'prints all deltas from Jan 1 \'92 to Dec 31 \'92 … [See Man Page]'

