# bk-send
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-send.1
# using Deroffing man parser
complete -c bk-send -o 's\\*<subject\\*>' --description '-d Prepend the patch with unified diffs.'
complete -c bk-send -s d --description 'Prepend the patch with unified diffs.'
complete -c bk-send -s f --description 'send the patch even if  believes the remote rep… [See Man Page]'
complete -c bk-send -s q --description 'Be quiet.  Specify the list of changesets to send.'

