# bk-stripdel
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-stripdel.1
# using Deroffing man parser
complete -c bk-stripdel -s C --description 'Do not respect cset boundaries, used by  bk undo .'
complete -c bk-stripdel -s c --description 'Checks if the specified rev[s] can be stripped … [See Man Page]'
complete -c bk-stripdel -s d --description 'Strip deltas which are part of a.'
complete -c bk-stripdel -s q --description 'Run quietly.  Set of revisions to be removed.'

