# bk-superset
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-superset.1
# using Deroffing man parser
complete -c bk-superset -s q --description 'Be quiet EXIT STATUS bk superset returns exit status.'

