# bk-takepatch
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-takepatch.1
# using Deroffing man parser
complete -c bk-takepatch -s a --description 'Apply the changes (call  bk resolve . ).'
complete -c bk-takepatch -s c --description 'Do not accept conflicts with this patch.  Take the patch from .'
complete -c bk-takepatch -s i --description 'Initial patch, create a new repository.'
complete -c bk-takepatch -l no-automerge --description 'Takepatch will try to automerge the file as par… [See Man Page]'
complete -c bk-takepatch -s S --description 'Save RESYNC and or PENDING directories even if errors.'
complete -c bk-takepatch -s T --description 'Run in text only mode, do not use GUI tools.'
complete -c bk-takepatch -s v --description 'Verbose level, more is more verbose,.'

