# bk-terms
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-terms.1
# using Deroffing man parser
complete -c bk-terms -o 'r1.23' --description '.'
complete -c bk-terms -o r3dcc5f35PWiRWg8wiP7Dehy51Pk7DA --description '.'
complete -c bk-terms -o 'r\'amy@bitkeeper.com' --description '.'
complete -c bk-terms -o 'r@1.233.2' --description '.'
complete -c bk-terms -o 'r@bk-3.0-pre3' --description '.'
complete -c bk-terms -o 'r@\'lm@disks.bitkeeper.com' --description 'ChangeSet The file used to record the repositor… [See Man Page]'

