# bk-unpull
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-unpull.1
# using Deroffing man parser
complete -c bk-unpull -s f --description 'Force unpull.'
complete -c bk-unpull -s q --description 'Quiet mode.'
complete -c bk-unpull -s S --description '.'
complete -c bk-unpull -l standalone --description 'In a nested collection this makes unpull operat… [See Man Page]'
complete -c bk-unpull -s s --description 'Do not save a backup patch in BitKeeper/tmp/unpull. patch .'

