# bk-undos
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-undos.1
# using Deroffing man parser
complete -c bk-undos -s n --description 'Prevents adding a missing trailing.'
complete -c bk-undos -s r --description 'Reverses the process and converts a UNIX file t… [See Man Page]'

