# bk-unedit
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-unedit.1
# using Deroffing man parser
complete -c bk-unedit -s q --description 'be quiet.  SEE ALSO CATEGORY File.'

