# bk-uninstall
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-uninstall.1
# using Deroffing man parser
complete -c bk-uninstall -s f --description 'Force uninstallation; do not prompt.  SEE ALSO.'

