# bk-version
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bk-version.1
# using Deroffing man parser
complete -c bk-version -s s --description 'Print just the version number (either ""NOTE.'

