# bkd
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/bkd.1
# using Deroffing man parser
complete -c bkd -s C --description 'This option provides a slightly more secure mod… [See Man Page]'
complete -c bkd -s d --description 'Run as a daemon, typically in the background (b… [See Man Page]'
complete -c bkd -s D --description 'Debug mode, do not fork and run in the background.'
complete -c bkd -s h --description 'For all outgoing bk push , bk pull , and bk clo… [See Man Page]'
complete -c bkd -o 'p\\fI' --description '.'
complete -c bkd -s S --description 'Run in "symlinks are allowed" safe mode.'
complete -c bkd -s U --description 'Run in "unsafe" mode.'

