# cdcontexttool
# Autogenerated from man page /usr/share/man/man1/cdcontexttool.1
# using Darwin man parser
complete -c cdcontexttool -s a --description 'Description of -a flag.'
complete -c cdcontexttool -s b --description 'Description of -b flag \\" Ends the list Pp .'

