# cdinteracttool
# Autogenerated from man page /usr/share/man/man1/cdinteracttool.1
# using Darwin man parser
complete -c cdinteracttool -s a --description 'Description of -a flag.'
complete -c cdinteracttool -s b --description 'Description of -b flag \\" Ends the list Pp .'

