# cdknowledgetool
# Autogenerated from man page /usr/share/man/man1/cdknowledgetool.1
# using Darwin man parser
complete -c cdknowledgetool -s a --description 'Description of -a flag.'
complete -c cdknowledgetool -s b --description 'Description of -b flag \\" Ends the list Pp .'

