# check
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/check.1
# using Deroffing man parser
complete -c check -s a --description 'Ensures that the ChangeSet file and the reposit… [See Man Page]'
complete -c check -s c --description 'Check file and the per delta checksums.'
complete -c check -s d --description 'Provide more details about what is wrong.'
complete -c check -s e --description 'Check for end of line (eoln) inconsistencies in text files.'
complete -c check -s f --description 'Fix any fixable errors.'
complete -c check -o ff --description 'Fix any fixable errors which have destructive fixes.'
complete -c check -s g --description 'List each missing file as the file\'s identifier… [See Man Page]'
complete -c check -o gg --description 'List each missing delta key, but do not produce… [See Man Page]'
complete -c check -o ggg --description 'List both missing files and missing deltas.'
complete -c check -s p --description 'List deltas which are in more than one changeset.'
complete -c check -s R --description 'Only do checks which make sense in the RESYNC dir.'
complete -c check -s v --description 'Be more verbose.   Each.'
complete -c check -s w --description 'List files which are writable but not locked.'

