# checksum
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/checksum.1
# using Deroffing man parser
complete -c checksum -s s --description 'option.'
complete -c checksum -s f --description 'option unless you are very sure of what you are doing.'
complete -c checksum -l safe-fix --description 'Only do fixes which do not alter the deltakey.'
complete -c checksum -s v --description 'be verbose.  SEE ALSO.'

