# citool
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/citool.1
# using Deroffing man parser
complete -c citool -l no-extras --description 'citool will look only for modified and/or pendi… [See Man Page]'

