# clean
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/clean.1
# using Deroffing man parser
complete -c clean -s p --description 'Prints diffs for all modified files.'
complete -c clean -s q --description 'Run quietly.'
complete -c clean -s v --description 'Run verbosely.  SEE ALSO CATEGORY Common.'

