# cmdlog
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/cmdlog.1
# using Deroffing man parser
complete -c cmdlog -s a --description 'List history of all commands run in the reposit… [See Man Page]'
complete -c cmdlog -s r --description 'List command start and stops with relative times.   Implies -a.'
complete -c cmdlog -s v --description 'Each line of output is prefixed with userid, ti… [See Man Page]'
complete -c cmdlog -s S --description '.'
complete -c cmdlog -l standalone --description 'When used in a nested collection, only process … [See Man Page]'
complete -c cmdlog -o av --description 'options, both the start and finish of commands … [See Man Page]'

