# collapse
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/collapse.1
# using Deroffing man parser
complete -c collapse -s l --description 'option to bk collapse saves a list of the md5ke… [See Man Page]'
complete -c collapse -s e --description 'Leave the resulting changes as locked, modified… [See Man Page]'
complete -c collapse -s S --description '.'
complete -c collapse -l standalone --description 'Just collapse the current component.'
complete -c collapse -l no-save --description 'when fixing the entire changeset the normal beh… [See Man Page]'
complete -c collapse -s q --description 'suppress most messages EXAMPLES Fix a problem i… [See Man Page]'

