# comments
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/comments.1
# using Deroffing man parser
complete -c comments -s p --description 'Generate the list of all comments in the files … [See Man Page]'

