# commit
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/commit.1
# using Deroffing man parser
complete -c commit -s c --description 'Use comments saved by a previous run of citool,… [See Man Page]'
complete -c commit -l ci --description 'Check in any edited files as part of the commit.'
complete -c commit -s f --description 'Don\'t run interactively; do the commit with the… [See Man Page]'
complete -c commit -s q --description 'Run quietly.'
complete -c commit -o sALIAS --description 'Commit all pending files in the given aliases a… [See Man Page]'
complete -c commit -o sPRODUCT --description 'if the top level commit is not wanted.'
complete -c commit -s S --description '.'
complete -c commit -l standalone --description 'Commit only in the current repository.  }.'
complete -c commit -l tag --description '.'

