# comps
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/comps.1
# using Deroffing man parser
complete -c comps -s h --description 'Only list components currently populated, or "here".'
complete -c comps -s k --description 'Instead of the default relative paths from the … [See Man Page]'
complete -c comps -s m --description 'Only list components not currently populated, or "missing".'

