# conflicts
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/conflicts.1
# using Deroffing man parser
complete -c conflicts -s d --description 'Invoke bk diffs on the file, showing the differ… [See Man Page]'
complete -c conflicts -s D --description 'Like.'
complete -c conflicts -s f --description 'Invoke the 3-way filemerge in read-only mode.'
complete -c conflicts -s r --description 'Invoke revtool, highlighting the GCA, LOCAL, an… [See Man Page]'
complete -c conflicts -s S --description 'When  used in a nested collection, treat the re… [See Man Page]'
complete -c conflicts -s v --description 'Verbose listing.'
complete -c conflicts -o vv --description 'More verbose listing.'

