# csetprune
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/csetprune.1
# using Deroffing man parser
complete -c csetprune -s S --description '.'
complete -c csetprune -l standalone --description 'Just run csetprune on the current component.'
complete -c csetprune -l tag-csets --description 'Alter the symbol structure to remove duplicates… [See Man Page]'

