# detach
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/detach.1
# using Deroffing man parser
complete -c detach -s q --description 'Run quietly.  Clone the repository up to and including cset .'

