# diff
# Autogenerated from man page /usr/share/man/man1/diff.1
# using Deroffing man parser
complete -c diff -l ignore-file-name-case --description 'Ignore case when comparing file names.'
complete -c diff -l no-ignore-file-name-case --description 'Consider case when comparing file names.'
complete -c diff -s E -l ignore-tab-expansion --description 'Ignore changes due to tab expansion.'
complete -c diff -l strip-trailing-cr --description 'Strip trailing carriage return on input.'
complete -c diff -l 'context[' --description 'Output NUM (default 3) lines of copied context.'
complete -c diff -l normal --description 'Output a normal diff.'
complete -c diff -l GTYPE-group-format --description 'Similar, but format GTYPE input groups with GFMT.'
complete -c diff -l LTYPE-line-format --description 'Similar, but format LTYPE input lines with LFMT.'
complete -c diff -l help --description 'Output this help.'

