# difftool
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/difftool.1
# using Deroffing man parser
complete -c difftool -s b --description 'Ignore changes in amount of white space.'
complete -c difftool -s S --description '.'
complete -c difftool -l standalone --description 'When  used in a nested collection, treat  the  … [See Man Page]'
complete -c difftool -s w --description 'Ignore white space when comparing lines.'
complete -c difftool -o r@cset --description 'then the set of files displayed is based on the… [See Man Page]'

