# edgepaint
# Autogenerated from man page /usr/local/share/man/man1/edgepaint.1
# using Deroffing man parser
complete -c edgepaint -o accuracy --description 'accuracy with which to find the maximally diffe… [See Man Page]'
complete -c edgepaint -o angle --description 'color two edges differently if their incidence … [See Man Page]'
complete -c edgepaint -o random_seed --description 'random seed to use.  s must be an integer.'
complete -c edgepaint -o lightness --description 'only applies for the "lab" color scheme: l1 and… [See Man Page]'
complete -c edgepaint -o share_endpoint --description 'if this option is specified, edges that shares … [See Man Page]'
complete -c edgepaint -s o --description 'write output to file f (default: stdout).'
complete -c edgepaint -o color_scheme --description 'specifies the color scheme.'
complete -c edgepaint -s v --description 'turns on verbose mode.'
complete -c edgepaint -s '?' --description 'Print usage and exit.'

