# edit
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/edit.1
# using Deroffing man parser
complete -c edit -s q --description 'run quietly Edit the file, rolling it back to t… [See Man Page]'

