# env
# Autogenerated from man page /usr/share/man/man1/env.1
# using Darwin man parser
complete -c env -s i --description 'Execute the utility with only those environment… [See Man Page]'
complete -c env -s P --description 'Search the set of directories as specified by a… [See Man Page]'
complete -c env -s S --description 'Split apart the given string into multiple stri… [See Man Page]'
complete -c env -s u --description 'If the environment variable name is in the envi… [See Man Page]'
complete -c env -s v --description 'Print verbose information for each step of proc… [See Man Page]'

