# fast-export
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/fast-export.1
# using Deroffing man parser
complete -c fast-export -l incremental --description 'Do an incremental export starting from the last… [See Man Page]'
complete -c fast-export -l no-bk-keys --description '.'
complete -c fast-export -s q --description '.'
complete -c fast-export -l quiet --description 'Don\'t print warnings or other information.'
complete -c fast-export -s S --description '.'
complete -c fast-export -l standalone --description 'When used in a nested collection, export only t… [See Man Page]'
complete -c fast-export -l branch --description 'option to fast-export each time.'

