# features
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/features.1
# using Deroffing man parser
complete -c features -l all --description 'lists all optional features known by this versi… [See Man Page]'

