# fixtool
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/fixtool.1
# using Deroffing man parser
complete -c fixtool -s f --description 'forces the answer to all prompts to be.'
complete -c fixtool -s p --description 'passed through to  bk diffs to get procedural diffs.'
complete -c fixtool -s s --description 'passed through to  bk diffs to get side-by-side diffs.'
complete -c fixtool -s u --description 'passed through to  bk diffs to get unified diffs.'
complete -c fixtool -s w --description 'passed through to  bk diffs to ignore whitespace in diffs.'

