# fm3tool
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/fm3tool.1
# using Deroffing man parser
complete -c fm3tool -s f --description 'force overwrite of existing file.'
complete -c fm3tool -s n --description 'do not write any merged output, put the tool in readonly mode.'

