# footprint
# Autogenerated from man page /usr/share/man/man1/footprint.1
# using Darwin man parser
complete -c footprint -s a --description 'target all processes (will take much longer).'
complete -c footprint -s j --description 'format output in JSON instead of structured text.'
complete -c footprint -s t --description 'in addition to the supplied processes, target t… [See Man Page]'
complete -c footprint -s s --description 'skip processes that are dirty tracked and have … [See Man Page]'
complete -c footprint -s v --description 'display vmmap-like output of address space layout.'
complete -c footprint -s h --description 'display help and exit El SAMPLE USAGE Pp footpr… [See Man Page]'

