# gate
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/gate.1
# using Deroffing man parser
complete -c gate -s q --description 'the exit status indicates gate status; 0 means … [See Man Page]'
complete -c gate -s r --description 'Unmark the nested collection as a gate.'

