# gbasename
# Autogenerated from man page /usr/local/share/man/man1/gbasename.1
# using Deroffing man parser
complete -c gbasename -s a -l multiple --description 'support multiple arguments and treat each as a NAME.'
complete -c gbasename -s s -l suffix --description 'remove a trailing SUFFIX; implies -a.'
complete -c gbasename -s z -l zero --description 'end each output line with NUL, not newline.'
complete -c gbasename -l help --description 'display this help and exit.'
complete -c gbasename -l version --description 'output version information and exit EXAMPLES.'
complete -c gbasename -s '>' --description '.'

