# gbase64
# Autogenerated from man page /usr/local/share/man/man1/gbase64.1
# using Deroffing man parser
complete -c gbase64 -s d -l decode --description 'decode data.'
complete -c gbase64 -s i -l ignore-garbage --description 'when decoding, ignore non-alphabet characters.'
complete -c gbase64 -s w -l wrap --description 'wrap encoded lines after COLS character (default 76).'
complete -c gbase64 -l help --description 'display this help and exit.'
complete -c gbase64 -l version --description 'output version information and exit.'

