# gcat
# Autogenerated from man page /usr/local/share/man/man1/gcat.1
# using Deroffing man parser
complete -c gcat -s A -l show-all --description 'equivalent to -vET.'
complete -c gcat -s b -l number-nonblank --description 'number nonempty output lines, overrides -n.'
complete -c gcat -s e --description 'equivalent to -vE.'
complete -c gcat -s E -l show-ends --description 'display $ at end of each line.'
complete -c gcat -s n -l number --description 'number all output lines.'
complete -c gcat -s s -l squeeze-blank --description 'suppress repeated empty output lines.'
complete -c gcat -s t --description 'equivalent to -vT.'
complete -c gcat -s T -l show-tabs --description 'display TAB characters as ^I.'
complete -c gcat -s u --description '(ignored).'
complete -c gcat -s v -l show-nonprinting --description 'use ^ and M- notation, except for LFD and TAB.'
complete -c gcat -l help --description 'display this help and exit.'
complete -c gcat -l version --description 'output version information and exit EXAMPLES.'

