# gchcon
# Autogenerated from man page /usr/local/share/man/man1/gchcon.1
# using Deroffing man parser
complete -c gchcon -l dereference --description 'affect the referent of each symbolic link (this… [See Man Page]'
complete -c gchcon -s h -l no-dereference --description 'affect symbolic links instead of any referenced file.'
complete -c gchcon -s u -l user --description 'set user USER in the target security context.'
complete -c gchcon -s r -l role --description 'set role ROLE in the target security context.'
complete -c gchcon -s t -l type --description 'set type TYPE in the target security context.'
complete -c gchcon -s l -l range --description 'set range RANGE in the target security context.'
complete -c gchcon -l no-preserve-root --description 'do not treat \'/\' specially (the default).'
complete -c gchcon -l preserve-root --description 'fail to operate recursively on \'/\'.'
complete -c gchcon -l reference --description 'use RFILE\'s security context rather than specif… [See Man Page]'
complete -c gchcon -s R -l recursive --description 'operate on files and directories recursively.'
complete -c gchcon -s v -l verbose --description 'output a diagnostic for every file processed .'
complete -c gchcon -s H --description 'if a command line argument is a symbolic link t… [See Man Page]'
complete -c gchcon -s L --description 'traverse every symbolic link to a directory encountered.'
complete -c gchcon -s P --description 'do not traverse any symbolic links (default).'
complete -c gchcon -l help --description 'display this help and exit.'
complete -c gchcon -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

