# gchgrp
# Autogenerated from man page /usr/local/share/man/man1/gchgrp.1
# using Deroffing man parser
complete -c gchgrp -s c -l changes --description 'like verbose but report only when a change is made.'
complete -c gchgrp -s f -l silent -l quiet --description 'suppress most error messages.'
complete -c gchgrp -s v -l verbose --description 'output a diagnostic for every file processed.'
complete -c gchgrp -l dereference --description 'affect the referent of each symbolic link (this… [See Man Page]'
complete -c gchgrp -s h -l no-dereference --description 'affect symbolic links instead of any referenced… [See Man Page]'
complete -c gchgrp -l no-preserve-root --description 'do not treat \'/\' specially (the default).'
complete -c gchgrp -l preserve-root --description 'fail to operate recursively on \'/\'.'
complete -c gchgrp -l reference --description 'use RFILE\'s group rather than specifying a GROUP value.'
complete -c gchgrp -s R -l recursive --description 'operate on files and directories recursively .'
complete -c gchgrp -s H --description 'if a command line argument is a symbolic link t… [See Man Page]'
complete -c gchgrp -s L --description 'traverse every symbolic link to a directory encountered.'
complete -c gchgrp -s P --description 'do not traverse any symbolic links (default).'
complete -c gchgrp -l help --description 'display this help and exit.'
complete -c gchgrp -l version --description 'output version information and exit EXAMPLES.'

