# gchmod
# Autogenerated from man page /usr/local/share/man/man1/gchmod.1
# using Deroffing man parser
complete -c gchmod -s c -l changes --description 'like verbose but report only when a change is made.'
complete -c gchmod -s f -l silent -l quiet --description 'suppress most error messages.'
complete -c gchmod -s v -l verbose --description 'output a diagnostic for every file processed.'
complete -c gchmod -l no-preserve-root --description 'do not treat \'/\' specially (the default).'
complete -c gchmod -l preserve-root --description 'fail to operate recursively on \'/\'.'
complete -c gchmod -l reference --description 'use RFILE\'s mode instead of MODE values.'
complete -c gchmod -s R -l recursive --description 'change files and directories recursively.'
complete -c gchmod -l help --description 'display this help and exit.'
complete -c gchmod -l version --description 'output version information and exit.'

