# gchown
# Autogenerated from man page /usr/local/share/man/man1/gchown.1
# using Deroffing man parser
complete -c gchown -s c -l changes --description 'like verbose but report only when a change is made.'
complete -c gchown -s f -l silent -l quiet --description 'suppress most error messages.'
complete -c gchown -s v -l verbose --description 'output a diagnostic for every file processed.'
complete -c gchown -l dereference --description 'affect the referent of each symbolic link (this… [See Man Page]'
complete -c gchown -s h -l no-dereference --description 'affect symbolic links instead of any referenced… [See Man Page]'
complete -c gchown -l from --description 'change the owner and/or group of each file only… [See Man Page]'
complete -c gchown -l no-preserve-root --description 'do not treat \'/\' specially (the default).'
complete -c gchown -l preserve-root --description 'fail to operate recursively on \'/\'.'
complete -c gchown -l reference --description 'use RFILE\'s owner and group rather than specify… [See Man Page]'
complete -c gchown -s R -l recursive --description 'operate on files and directories recursively .'
complete -c gchown -s H --description 'if a command line argument is a symbolic link t… [See Man Page]'
complete -c gchown -s L --description 'traverse every symbolic link to a directory encountered.'
complete -c gchown -s P --description 'do not traverse any symbolic links (default).'
complete -c gchown -l help --description 'display this help and exit.'
complete -c gchown -l version --description 'output version information and exit.'

