# gchroot
# Autogenerated from man page /usr/local/share/man/man1/gchroot.1
# using Deroffing man parser
complete -c gchroot -l groups --description 'specify supplementary groups as g1,g2,. ,gN.'
complete -c gchroot -l userspec --description 'specify user and group (ID or name) to use.'
complete -c gchroot -l skip-chdir --description 'do not change working directory to \'/\'.'
complete -c gchroot -l help --description 'display this help and exit.'
complete -c gchroot -l version --description 'output version information and exit.'

