# gcksum
# Autogenerated from man page /usr/local/share/man/man1/gcksum.1
# using Deroffing man parser
complete -c gcksum -l help --description 'display this help and exit.'
complete -c gcksum -l version --description 'output version information and exit AUTHOR Written by Q.'

