# gcomm
# Autogenerated from man page /usr/local/share/man/man1/gcomm.1
# using Deroffing man parser
complete -c gcomm -s 1 --description 'suppress column 1 (lines unique to FILE1).'
complete -c gcomm -s 2 --description 'suppress column 2 (lines unique to FILE2).'
complete -c gcomm -s 3 --description 'suppress column 3 (lines that appear in both files).'
complete -c gcomm -l check-order --description 'check that the input is correctly sorted, even … [See Man Page]'
complete -c gcomm -l nocheck-order --description 'do not check that the input is correctly sorted.'
complete -c gcomm -l output-delimiter --description 'separate columns with STR.'
complete -c gcomm -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c gcomm -l help --description 'display this help and exit.'
complete -c gcomm -l version --description 'output version information and exit.'

