# gcsplit
# Autogenerated from man page /usr/local/share/man/man1/gcsplit.1
# using Deroffing man parser
complete -c gcsplit -s b -l suffix-format --description 'use sprintf FORMAT instead of %02d.'
complete -c gcsplit -s f -l prefix --description 'use PREFIX instead of \'xx\'.'
complete -c gcsplit -s k -l keep-files --description 'do not remove output files on errors.'
complete -c gcsplit -l suppress-matched --description 'suppress the lines matching PATTERN.'
complete -c gcsplit -s n -l digits --description 'use specified number of digits instead of 2.'
complete -c gcsplit -s s -l quiet -l silent --description 'do not print counts of output file sizes.'
complete -c gcsplit -s z -l elide-empty-files --description 'remove empty output files.'
complete -c gcsplit -l help --description 'display this help and exit.'
complete -c gcsplit -l version --description 'output version information and exit .'

