# gcut
# Autogenerated from man page /usr/local/share/man/man1/gcut.1
# using Deroffing man parser
complete -c gcut -s b -l bytes --description 'select only these bytes.'
complete -c gcut -s c -l characters --description 'select only these characters.'
complete -c gcut -s d -l delimiter --description 'use DELIM instead of TAB for field delimiter.'
complete -c gcut -s f -l fields --description 'select only these fields;  also print any line … [See Man Page]'
complete -c gcut -s n --description '(ignored).'
complete -c gcut -l complement --description 'complement the set of selected bytes, characters or fields.'
complete -c gcut -s s -l only-delimited --description 'do not print lines not containing delimiters.'
complete -c gcut -l output-delimiter --description 'use STRING as the output delimiter the default … [See Man Page]'
complete -c gcut -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c gcut -l help --description 'display this help and exit.'
complete -c gcut -l version --description 'output version information and exit .'
complete -c gcut -s M --description 'from first to M\'th (included) byte, character o… [See Man Page]'

