# gdate
# Autogenerated from man page /usr/local/share/man/man1/gdate.1
# using Deroffing man parser
complete -c gdate -s d -l date --description 'display time described by STRING, not \'now\'.'
complete -c gdate -s f -l file --description 'like --date; once for each line of DATEFILE.'
complete -c gdate -o 'I[FMT]' -l 'iso-8601[' --description 'output date/time in ISO 8601 format.'
complete -c gdate -s R -l rfc-2822 --description 'output date and time in RFC 2822 format.'
complete -c gdate -l rfc-3339 --description 'output date/time in RFC 3339 format.'
complete -c gdate -s r -l reference --description 'display the last modification time of FILE.'
complete -c gdate -s s -l set --description 'set time described by STRING.'
complete -c gdate -s u -l utc -l universal --description 'print or set Coordinated Universal Time (UTC).'
complete -c gdate -l help --description 'display this help and exit.'
complete -c gdate -l version --description 'output version information and exit .'

