# gdd
# Autogenerated from man page /usr/local/share/man/man1/gdd.1
# using Deroffing man parser
complete -c gdd -l help --description 'display this help and exit.'
complete -c gdd -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

