# gdf
# Autogenerated from man page /usr/local/share/man/man1/gdf.1
# using Deroffing man parser
complete -c gdf -s a -l all --description 'include pseudo, duplicate, inaccessible file systems.'
complete -c gdf -s B -l block-size --description 'scale sizes by SIZE before printing them; e. g.'
complete -c gdf -s h -l human-readable --description 'print sizes in powers of 1024 (e. g. , 1023M).'
complete -c gdf -s H -l si --description 'print sizes in powers of 1000 (e. g. , 1. 1G).'
complete -c gdf -s i -l inodes --description 'list inode information instead of block usage.'
complete -c gdf -s k --description 'like --block-size=\\,1K\\/.'
complete -c gdf -s l -l local --description 'limit listing to local file systems.'
complete -c gdf -l no-sync --description 'do not invoke sync before getting usage info (default).'
complete -c gdf -l 'output[' --description 'use the output format defined by FIELD_LIST, or… [See Man Page]'
complete -c gdf -s P -l portability --description 'use the POSIX output format.'
complete -c gdf -l sync --description 'invoke sync before getting usage info.'
complete -c gdf -l total --description 'elide all entries insignificant to available sp… [See Man Page]'
complete -c gdf -s t -l type --description 'limit listing to file systems of type TYPE.'
complete -c gdf -s T -l print-type --description 'print file system type.'
complete -c gdf -s x -l exclude-type --description 'limit listing to file systems not of type TYPE.'
complete -c gdf -s v --description '(ignored).'
complete -c gdf -l help --description 'display this help and exit.'
complete -c gdf -l version --description 'output version information and exit.'

