# gdirname
# Autogenerated from man page /usr/local/share/man/man1/gdirname.1
# using Deroffing man parser
complete -c gdirname -s z -l zero --description 'end each output line with NUL, not newline.'
complete -c gdirname -l help --description 'display this help and exit.'
complete -c gdirname -l version --description 'output version information and exit EXAMPLES.'
complete -c gdirname -s '>' --description '.'

