# gdircolors
# Autogenerated from man page /usr/local/share/man/man1/gdircolors.1
# using Deroffing man parser
complete -c gdircolors -s b -l sh -l bourne-shell --description 'output Bourne shell code to set LS_COLORS.'
complete -c gdircolors -s c -l csh -l c-shell --description 'output C shell code to set LS_COLORS.'
complete -c gdircolors -s p -l print-database --description 'output defaults.'
complete -c gdircolors -l help --description 'display this help and exit.'
complete -c gdircolors -l version --description 'output version information and exit.'

