# gecho
# Autogenerated from man page /usr/local/share/man/man1/gecho.1
# using Deroffing man parser
complete -c gecho -s n --description 'do not output the trailing newline.'
complete -c gecho -s e --description 'enable interpretation of backslash escapes.'
complete -c gecho -s E --description 'disable interpretation of backslash escapes (default).'
complete -c gecho -l help --description 'display this help and exit.'
complete -c gecho -l version --description 'output version information and exit .'

