# genv
# Autogenerated from man page /usr/local/share/man/man1/genv.1
# using Deroffing man parser
complete -c genv -s i -l ignore-environment --description 'start with an empty environment.'
complete -c genv -s 0 -l null --description 'end each output line with NUL, not newline.'
complete -c genv -s u -l unset --description 'remove variable from the environment.'
complete -c genv -l help --description 'display this help and exit.'
complete -c genv -l version --description 'output version information and exit.'

