# gethost
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/gethost.1
# using Deroffing man parser
complete -c gethost -s n --description 'print the internet address instead of the host.'
complete -c gethost -s r --description 'print the real host name, ignoring.'

