# gexpr
# Autogenerated from man page /usr/local/share/man/man1/gexpr.1
# using Deroffing man parser
complete -c gexpr -l help --description 'display this help and exit.'
complete -c gexpr -l version --description 'output version information and exit .'

