# gfactor
# Autogenerated from man page /usr/local/share/man/man1/gfactor.1
# using Deroffing man parser
complete -c gfactor -l help --description 'display this help and exit.'
complete -c gfactor -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

