# gfmt
# Autogenerated from man page /usr/local/share/man/man1/gfmt.1
# using Deroffing man parser
complete -c gfmt -s c -l crown-margin --description 'preserve indentation of first two lines.'
complete -c gfmt -s p -l prefix --description 'reformat only lines beginning with STRING, reat… [See Man Page]'
complete -c gfmt -s s -l split-only --description 'split long lines, but do not refill.'
complete -c gfmt -s t -l tagged-paragraph --description 'indentation of first line different from second.'
complete -c gfmt -s u -l uniform-spacing --description 'one space between words, two after sentences.'
complete -c gfmt -s w -l width --description 'maximum line width (default of 75 columns).'
complete -c gfmt -s g -l goal --description 'goal width (default of 93% of width).'
complete -c gfmt -l help --description 'display this help and exit.'
complete -c gfmt -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

