# gfold
# Autogenerated from man page /usr/local/share/man/man1/gfold.1
# using Deroffing man parser
complete -c gfold -s b -l bytes --description 'count bytes rather than columns.'
complete -c gfold -s s -l spaces --description 'break at spaces.'
complete -c gfold -s w -l width --description 'use WIDTH columns instead of 80.'
complete -c gfold -l help --description 'display this help and exit.'
complete -c gfold -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

