# ggroups
# Autogenerated from man page /usr/local/share/man/man1/ggroups.1
# using Deroffing man parser
complete -c ggroups -l help --description 'display this help and exit.'
complete -c ggroups -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

