# ghostid
# Autogenerated from man page /usr/local/share/man/man1/ghostid.1
# using Deroffing man parser
complete -c ghostid -l help --description 'display this help and exit.'
complete -c ghostid -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

