# gid
# Autogenerated from man page /usr/local/share/man/man1/gid.1
# using Deroffing man parser
complete -c gid -s a --description 'ignore, for compatibility with other versions.'
complete -c gid -s Z -l context --description 'print only the security context of the process.'
complete -c gid -s g -l group --description 'print only the effective group ID.'
complete -c gid -s G -l groups --description 'print all group IDs.'
complete -c gid -s n -l name --description 'print a name instead of a number, for -ugG.'
complete -c gid -s r -l real --description 'print the real ID instead of the effective ID, with -ugG.'
complete -c gid -s u -l user --description 'print only the effective user ID.'
complete -c gid -s z -l zero --description 'delimit entries with NUL characters, not whites… [See Man Page]'
complete -c gid -l help --description 'display this help and exit.'
complete -c gid -l version --description 'output version information and exit.'

