# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
# using Deroffing man parser
complete -c git-config -l show-origin --description 'Augment the output of all queried config option… [See Man Page]'
complete -c git-config -l negotiate --description 'curl(1)) oc o 2. 3.'
complete -c git-config -l ntlm --description 'curl(1)) http. emptyAuth.'

