# git-blame
# Autogenerated from man page /usr/local/share/man/man1/git-blame.1
# using Deroffing man parser
complete -c git-blame -l '[no-]progress' --description 'Progress status is reported on the standard err… [See Man Page]'
complete -c git-blame -l progress --description 'together with.'
complete -c git-blame -l 'incremental.' --description '.'

