# git-annotate
# Autogenerated from man page /usr/local/share/man/man1/git-annotate.1
# using Deroffing man parser
complete -c git-annotate -l '[no-]progress' --description 'Progress status is reported on the standard err… [See Man Page]'
complete -c git-annotate -l progress --description 'together with.'
complete -c git-annotate -l 'incremental.' --description '.'

