# git-pull
# Autogenerated from man page /usr/local/share/man/man1/git-pull.1
# using Deroffing man parser
complete -c git-pull -s 4 -l ipv4 --description 'Use IPv4 addresses only, ignoring IPv6 addresses.'
complete -c git-pull -s 6 -l ipv6 --description 'Use IPv6 addresses only, ignoring IPv4 addresses.'

