# git-ls-files
# Autogenerated from man page /usr/local/share/man/man1/git-ls-files.1
# using Deroffing man parser
complete -c git-ls-files -l eol --description 'Show <eolinfo> and <eolattr> of files.'

