# git-interpret-trailers
# Autogenerated from man page /usr/local/share/man/man1/git-interpret-trailers.1
# using Deroffing man parser
complete -c git-interpret-trailers -l in-place --description 'Edit the files in place.'

