# git-grep
# Autogenerated from man page /usr/local/share/man/man1/git-grep.1
# using Deroffing man parser
complete -c git-grep -l threads --description 'Number of grep worker threads to use.  See grep.'

