# git-update-index
# Autogenerated from man page /usr/local/share/man/man1/git-update-index.1
# using Deroffing man parser
complete -c git-update-index -l test-untracked-cache --description 'Only perform tests on the working directory to … [See Man Page]'
complete -c git-update-index -l 'untracked-cache.' --description '.'

