# git-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-fetch.1
# using Deroffing man parser
complete -c git-fetch -s j -l jobs --description 'Number of parallel children to be used for fetching submodules.'
complete -c git-fetch -s 4 -l ipv4 --description 'Use IPv4 addresses only, ignoring IPv6 addresses.'
complete -c git-fetch -s 6 -l ipv6 --description 'Use IPv6 addresses only, ignoring IPv4 addresses.'

