# git-ls-remote
# Autogenerated from man page /usr/local/share/man/man1/git-ls-remote.1
# using Deroffing man parser
complete -c git-ls-remote -l refs --description 'Do not show peeled tags or pseudorefs like HEAD in the output.'
complete -c git-ls-remote -s q -l quiet --description 'Do not print remote URL to stderr.'
complete -c git-ls-remote -l symref --description 'In addition to the object pointed by it, show t… [See Man Page]'

