# gjoin
# Autogenerated from man page /usr/local/share/man/man1/gjoin.1
# using Deroffing man parser
complete -c gjoin -s a --description 'also print unpairable lines from file FILENUM, … [See Man Page]'
complete -c gjoin -s e --description 'replace missing input fields with EMPTY.'
complete -c gjoin -s i -l ignore-case --description 'ignore differences in case when comparing fields.'
complete -c gjoin -s j --description 'equivalent to \'-1 FIELD -2 FIELD\'.'
complete -c gjoin -s o --description 'obey FORMAT while constructing output line.'
complete -c gjoin -s t --description 'use CHAR as input and output field separator.'
complete -c gjoin -s v --description 'like -a FILENUM, but suppress joined output lines.'
complete -c gjoin -s 1 --description 'join on this FIELD of file 1.'
complete -c gjoin -s 2 --description 'join on this FIELD of file 2.'
complete -c gjoin -l check-order --description 'check that the input is correctly sorted, even … [See Man Page]'
complete -c gjoin -l nocheck-order --description 'do not check that the input is correctly sorted.'
complete -c gjoin -l header --description 'treat the first line in each file as field head… [See Man Page]'
complete -c gjoin -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c gjoin -l help --description 'display this help and exit.'
complete -c gjoin -l version --description 'output version information and exit.'

