# gkill
# Autogenerated from man page /usr/local/share/man/man1/gkill.1
# using Deroffing man parser
complete -c gkill -s l -l list --description 'list signal names, or convert signal names to/from numbers.'
complete -c gkill -s t -l table --description 'print a table of signal information.'
complete -c gkill -l help --description 'display this help and exit.'
complete -c gkill -s s -l signal -o SIGNAL --description 'specify the name or number of the signal to be sent.'
complete -c gkill -l version --description 'output version information and exit.'

