# gln
# Autogenerated from man page /usr/local/share/man/man1/gln.1
# using Deroffing man parser
complete -c gln -l 'backup[' --description 'make a backup of each existing destination file.'
complete -c gln -s b --description 'like --backup but does not accept an argument.'
complete -c gln -s d -s F -l directory --description 'allow the superuser to attempt to hard link dir… [See Man Page]'
complete -c gln -s f -l force --description 'remove existing destination files.'
complete -c gln -s i -l interactive --description 'prompt whether to remove destinations.'
complete -c gln -s L -l logical --description 'dereference TARGETs that are symbolic links.'
complete -c gln -s n -l no-dereference --description 'treat LINK_NAME as a normal file if it is a sym… [See Man Page]'
complete -c gln -s P -l physical --description 'make hard links directly to symbolic links.'
complete -c gln -s r -l relative --description 'create symbolic links relative to link location.'
complete -c gln -s s -l symbolic --description 'make symbolic links instead of hard links.'
complete -c gln -s S -l suffix --description 'override the usual backup suffix.'
complete -c gln -s t -l target-directory --description 'specify the DIRECTORY in which to create the links.'
complete -c gln -s T -l no-target-directory --description 'treat LINK_NAME as a normal file always.'
complete -c gln -s v -l verbose --description 'print name of each linked file.'
complete -c gln -l help --description 'display this help and exit.'
complete -c gln -l version --description 'output version information and exit .'

