# gmkdir
# Autogenerated from man page /usr/local/share/man/man1/gmkdir.1
# using Deroffing man parser
complete -c gmkdir -s m -l mode --description 'set file mode (as in chmod), not a=rwx - umask.'
complete -c gmkdir -s p -l parents --description 'no error if existing, make parent directories as needed.'
complete -c gmkdir -s v -l verbose --description 'print a message for each created directory.'
complete -c gmkdir -s Z --description 'set SELinux security context of each created di… [See Man Page]'
complete -c gmkdir -l 'context[' --description 'like -Z, or if CTX is specified then set the SE… [See Man Page]'
complete -c gmkdir -l help --description 'display this help and exit.'
complete -c gmkdir -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

