# gmknod
# Autogenerated from man page /usr/local/share/man/man1/gmknod.1
# using Deroffing man parser
complete -c gmknod -s m -l mode --description 'set file permission bits to MODE, not a=rw - umask.'
complete -c gmknod -s Z --description 'set the SELinux security context to default type.'
complete -c gmknod -l 'context[' --description 'like -Z, or if CTX is specified then set the SE… [See Man Page]'
complete -c gmknod -l help --description 'display this help and exit.'
complete -c gmknod -l version --description 'output version information and exit .'

