# gmktemp
# Autogenerated from man page /usr/local/share/man/man1/gmktemp.1
# using Deroffing man parser
complete -c gmktemp -s d -l directory --description 'create a directory, not a file.'
complete -c gmktemp -s u -l dry-run --description 'do not create anything; merely print a name (unsafe).'
complete -c gmktemp -s q -l quiet --description 'suppress diagnostics about file/dir-creation failure.'
complete -c gmktemp -l suffix --description 'append SUFF to TEMPLATE; SUFF must not contain a slash.'
complete -c gmktemp -s p -l 'tmpdir[' --description 'interpret TEMPLATE relative to DIR; if DIR is n… [See Man Page]'
complete -c gmktemp -s t --description 'interpret TEMPLATE as a single file name compon… [See Man Page]'
complete -c gmktemp -l help --description 'display this help and exit.'
complete -c gmktemp -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

