# gmv
# Autogenerated from man page /usr/local/share/man/man1/gmv.1
# using Deroffing man parser
complete -c gmv -l 'backup[' --description 'make a backup of each existing destination file.'
complete -c gmv -s b --description 'like --backup but does not accept an argument.'
complete -c gmv -s f -l force --description 'do not prompt before overwriting.'
complete -c gmv -s i -l interactive --description 'prompt before overwrite.'
complete -c gmv -s n -l no-clobber --description 'do not overwrite an existing file .'
complete -c gmv -l strip-trailing-slashes --description 'remove any trailing slashes from each SOURCE argument.'
complete -c gmv -s S -l suffix --description 'override the usual backup suffix.'
complete -c gmv -s t -l target-directory --description 'move all SOURCE arguments into DIRECTORY.'
complete -c gmv -s T -l no-target-directory --description 'treat DEST as a normal file.'
complete -c gmv -s u -l update --description 'move only when the SOURCE file is newer than th… [See Man Page]'
complete -c gmv -s v -l verbose --description 'explain what is being done.'
complete -c gmv -s Z -l context --description 'set SELinux security context of destination fil… [See Man Page]'
complete -c gmv -l help --description 'display this help and exit.'
complete -c gmv -l version --description 'output version information and exit .'

