# gnice
# Autogenerated from man page /usr/local/share/man/man1/gnice.1
# using Deroffing man parser
complete -c gnice -s n -l adjustment --description 'add integer N to the niceness (default 10).'
complete -c gnice -l help --description 'display this help and exit.'
complete -c gnice -o 20 --description '.'
complete -c gnice -l version --description 'output version information and exit.'

