# gnl
# Autogenerated from man page /usr/local/share/man/man1/gnl.1
# using Deroffing man parser
complete -c gnl -s b -l body-numbering --description 'use STYLE for numbering body lines.'
complete -c gnl -s d -l section-delimiter --description 'use CC for separating logical pages.'
complete -c gnl -s f -l footer-numbering --description 'use STYLE for numbering footer lines.'
complete -c gnl -s h -l header-numbering --description 'use STYLE for numbering header lines.'
complete -c gnl -s i -l line-increment --description 'line number increment at each line.'
complete -c gnl -s l -l join-blank-lines --description 'group of NUMBER empty lines counted as one.'
complete -c gnl -s n -l number-format --description 'insert line numbers according to FORMAT.'
complete -c gnl -s p -l no-renumber --description 'do not reset line numbers at logical pages.'
complete -c gnl -s s -l number-separator --description 'add STRING after (possible) line number.'
complete -c gnl -s v -l starting-line-number --description 'first line number on each logical page.'
complete -c gnl -s w -l number-width --description 'use NUMBER columns for line numbers.'
complete -c gnl -l help --description 'display this help and exit.'
complete -c gnl -l version --description 'output version information and exit .'

