# gnohup
# Autogenerated from man page /usr/local/share/man/man1/gnohup.1
# using Deroffing man parser
complete -c gnohup -l help --description 'display this help and exit.'
complete -c gnohup -l version --description 'output version information and exit.'

