# gnproc
# Autogenerated from man page /usr/local/share/man/man1/gnproc.1
# using Deroffing man parser
complete -c gnproc -l all --description 'print the number of installed processors.'
complete -c gnproc -l ignore --description 'if possible, exclude N processing units.'
complete -c gnproc -l help --description 'display this help and exit.'
complete -c gnproc -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

