# gnumfmt
# Autogenerated from man page /usr/local/share/man/man1/gnumfmt.1
# using Deroffing man parser
complete -c gnumfmt -l debug --description 'print warnings about invalid input.'
complete -c gnumfmt -s d -l delimiter --description 'use X instead of whitespace for field delimiter.'
complete -c gnumfmt -l field --description 'replace the numbers in these input fields (defa… [See Man Page]'
complete -c gnumfmt -l format --description 'use printf style floating-point FORMAT; see FOR… [See Man Page]'
complete -c gnumfmt -l from --description 'auto-scale input numbers to UNITs; default is \'… [See Man Page]'
complete -c gnumfmt -l from-unit --description 'specify the input unit size (instead of the default 1).'
complete -c gnumfmt -l grouping --description 'use locale-defined grouping of digits, e. g.'
complete -c gnumfmt -l 'header[' --description 'print (without converting) the first N header l… [See Man Page]'
complete -c gnumfmt -l invalid --description 'failure mode for invalid numbers: MODE can be: … [See Man Page]'
complete -c gnumfmt -l padding --description 'pad the output to N characters; positive N will… [See Man Page]'
complete -c gnumfmt -l round --description 'use METHOD for rounding when scaling; METHOD ca… [See Man Page]'
complete -c gnumfmt -l suffix --description 'add SUFFIX to output numbers, and accept option… [See Man Page]'
complete -c gnumfmt -l to --description 'auto-scale output numbers to UNITs; see UNIT below.'
complete -c gnumfmt -l to-unit --description 'the output unit size (instead of the default 1).'
complete -c gnumfmt -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c gnumfmt -l help --description 'display this help and exit.'
complete -c gnumfmt -l version --description 'output version information and exit . SS "UNIT options:".'
complete -c gnumfmt -s M --description 'from first to M\'th field (inclusive).'
complete -c gnumfmt -s '>' --description '$ numfmt --to=iec 2048.'

