# gozilla
# Autogenerated from man page /usr/local/share/man/man1/gozilla.1
# using Deroffing man parser
complete -c gozilla -s b --description 'Browser to use.  By default, it is assumed mozilla.'
complete -c gozilla -s d --description 'Print definitions.'
complete -c gozilla -l help --description 'Show help.'
complete -c gozilla -s p --description 'Just print a generated URL instead of displaying it.'
complete -c gozilla -s q -l quiet --description 'Quiet mode.'
complete -c gozilla -s v -l verbose --description 'Verbose mode.'
complete -c gozilla -l version --description 'Show version number.  FILES.'

