# gpaste
# Autogenerated from man page /usr/local/share/man/man1/gpaste.1
# using Deroffing man parser
complete -c gpaste -s d -l delimiters --description 'reuse characters from LIST instead of TABs.'
complete -c gpaste -s s -l serial --description 'paste one file at a time instead of in parallel.'
complete -c gpaste -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c gpaste -l help --description 'display this help and exit.'
complete -c gpaste -l version --description 'output version information and exit AUTHOR Written by David M.'

