# gpathchk
# Autogenerated from man page /usr/local/share/man/man1/gpathchk.1
# using Deroffing man parser
complete -c gpathchk -s p --description 'check for most POSIX systems.'
complete -c gpathchk -s P --description 'check for empty names and leading "-".'
complete -c gpathchk -l portability --description 'check for all POSIX systems (equivalent to -p -P).'
complete -c gpathchk -l help --description 'display this help and exit.'
complete -c gpathchk -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

