# gpinky
# Autogenerated from man page /usr/local/share/man/man1/gpinky.1
# using Deroffing man parser
complete -c gpinky -s l --description 'produce long format output for the specified USERs.'
complete -c gpinky -s b --description 'omit the user\'s home directory and shell in long format.'
complete -c gpinky -s h --description 'omit the user\'s project file in long format.'
complete -c gpinky -s p --description 'omit the user\'s plan file in long format.'
complete -c gpinky -s s --description 'do short format output, this is the default.'
complete -c gpinky -s f --description 'omit the line of column headings in short format.'
complete -c gpinky -s w --description 'omit the user\'s full name in short format.'
complete -c gpinky -s i --description 'omit the user\'s full name and remote host in short format.'
complete -c gpinky -s q --description 'omit the user\'s full name, remote host and idle… [See Man Page]'
complete -c gpinky -l help --description 'display this help and exit.'
complete -c gpinky -l version --description 'output version information and exit.'

