# gprintf
# Autogenerated from man page /usr/local/share/man/man1/gprintf.1
# using Deroffing man parser
complete -c gprintf -l help --description 'display this help and exit.'
complete -c gprintf -l version --description 'output version information and exit .'

