# gprintenv
# Autogenerated from man page /usr/local/share/man/man1/gprintenv.1
# using Deroffing man parser
complete -c gprintenv -s 0 -l null --description 'end each output line with NUL, not newline.'
complete -c gprintenv -l help --description 'display this help and exit.'
complete -c gprintenv -l version --description 'output version information and exit.'

