# gptx
# Autogenerated from man page /usr/local/share/man/man1/gptx.1
# using Deroffing man parser
complete -c gptx -s A -l auto-reference --description 'output automatically generated references.'
complete -c gptx -s G -l traditional --description 'behave more like System V \'ptx\'.'
complete -c gptx -s F -l flag-truncation --description 'use STRING for flagging line truncations.  The default is \'/\'.'
complete -c gptx -s M -l macro-name --description 'macro name to use instead of \'xx\'.'
complete -c gptx -s O -l format --description 'generate output as roff directives.'
complete -c gptx -s R -l right-side-refs --description 'put references at right, not counted in -w.'
complete -c gptx -s S -l sentence-regexp --description 'for end of lines or end of sentences.'
complete -c gptx -s T --description 'generate output as TeX directives.'
complete -c gptx -s W -l word-regexp --description 'use REGEXP to match each keyword.'
complete -c gptx -s b -l break-file --description 'word break characters in this FILE.'
complete -c gptx -s f -l ignore-case --description 'fold lower case to upper case for sorting.'
complete -c gptx -s g -l gap-size --description 'gap size in columns between output fields.'
complete -c gptx -s i -l ignore-file --description 'read ignore word list from FILE.'
complete -c gptx -s o -l only-file --description 'read only word list from this FILE.'
complete -c gptx -s r -l references --description 'first field of each line is a reference .'
complete -c gptx -s w -l width --description 'output width in columns, reference excluded.'
complete -c gptx -l help --description 'display this help and exit.'
complete -c gptx -s t -l typeset-mode --description '.'
complete -c gptx -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

