# gpwd
# Autogenerated from man page /usr/local/share/man/man1/gpwd.1
# using Deroffing man parser
complete -c gpwd -s L -l logical --description 'use PWD from environment, even if it contains symlinks.'
complete -c gpwd -s P -l physical --description 'avoid all symlinks.'
complete -c gpwd -l help --description 'display this help and exit.'
complete -c gpwd -l version --description 'output version information and exit.'

