# greadlink
# Autogenerated from man page /usr/local/share/man/man1/greadlink.1
# using Deroffing man parser
complete -c greadlink -s f -l canonicalize --description 'canonicalize by following every symlink in ever… [See Man Page]'
complete -c greadlink -s e -l canonicalize-existing --description 'canonicalize by following every symlink in ever… [See Man Page]'
complete -c greadlink -s m -l canonicalize-missing --description 'canonicalize by following every symlink in ever… [See Man Page]'
complete -c greadlink -s n -l no-newline --description 'do not output the trailing delimiter . HP -q, --quiet,.'
complete -c greadlink -s s -l silent --description 'suppress most error messages.'
complete -c greadlink -s v -l verbose --description 'report error messages.'
complete -c greadlink -s z -l zero --description 'end each output line with NUL, not newline.'
complete -c greadlink -l help --description 'display this help and exit.'
complete -c greadlink -s q -l quiet --description '.'
complete -c greadlink -l version --description 'output version information and exit AUTHOR Written by Dmitry V.'

