# grmdir
# Autogenerated from man page /usr/local/share/man/man1/grmdir.1
# using Deroffing man parser
complete -c grmdir -s p -l parents --description 'remove DIRECTORY and its ancestors; e. g.'
complete -c grmdir -s v -l verbose --description 'output a diagnostic for every directory processed.'
complete -c grmdir -l help --description 'display this help and exit.'
complete -c grmdir -l ignore-fail-on-non-empty --description 'ignore each failure that is solely because a di… [See Man Page]'
complete -c grmdir -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

