# gruncon
# Autogenerated from man page /usr/local/share/man/man1/gruncon.1
# using Deroffing man parser
complete -c gruncon -s c -l compute --description 'compute process transition context before modifying.'
complete -c gruncon -s t -l type --description 'type (for same role as parent).'
complete -c gruncon -s u -l user --description 'user identity.'
complete -c gruncon -s r -l role --description 'role.'
complete -c gruncon -s l -l range --description 'levelrange.'
complete -c gruncon -l help --description 'display this help and exit.'
complete -c gruncon -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

