# gsed
# Autogenerated from man page /usr/local/share/man/man1/gsed.1
# using Deroffing man parser
complete -c gsed -l help --description 'display this help and exit.'
complete -c gsed -s n -l quiet -l silent --description 'suppress automatic printing of pattern space.'
complete -c gsed -s e -l expression --description 'add the script to the commands to be executed.'
complete -c gsed -s f -l file --description 'add the contents of script-file to the commands to be executed.'
complete -c gsed -l follow-symlinks --description 'follow symlinks when processing in place.'
complete -c gsed -o 'i[SUFFIX]' -l 'in-place[' --description 'edit files in place (makes backup if SUFFIX supplied).'
complete -c gsed -s l -l line-length --description 'specify the desired line-wrap length for the `l\' command.'
complete -c gsed -l posix --description 'disable all GNU extensions.'
complete -c gsed -s r -l regexp-extended --description 'use extended regular expressions in the script.'
complete -c gsed -s s -l separate --description 'consider files as separate rather than as a sin… [See Man Page]'
complete -c gsed -s u -l unbuffered --description 'load minimal amounts of data from the input fil… [See Man Page]'
complete -c gsed -s z -l null-data --description 'separate lines by NUL characters.'
complete -c gsed -l version --description 'output version information and exit.'

