# gseq
# Autogenerated from man page /usr/local/share/man/man1/gseq.1
# using Deroffing man parser
complete -c gseq -s f -l format --description 'use printf style floating-point FORMAT.'
complete -c gseq -s s -l separator --description 'use STRING to separate numbers (default: n).'
complete -c gseq -s w -l equal-width --description 'equalize width by padding with leading zeroes.'
complete -c gseq -l help --description 'display this help and exit.'
complete -c gseq -l version --description 'output version information and exit.'

