# gsha384sum
# Autogenerated from man page /usr/local/share/man/man1/gsha384sum.1
# using Deroffing man parser
complete -c gsha384sum -s b -l binary --description 'read in binary mode.'
complete -c gsha384sum -s c -l check --description 'read SHA384 sums from the FILEs and check them.'
complete -c gsha384sum -l tag --description 'create a BSD-style checksum.'
complete -c gsha384sum -s t -l text --description 'read in text mode (default) .'
complete -c gsha384sum -l ignore-missing --description 'don\'t fail or report status for missing files.'
complete -c gsha384sum -l quiet --description 'don\'t print OK for each successfully verified file.'
complete -c gsha384sum -l status --description 'don\'t output anything, status code shows success.'
complete -c gsha384sum -l strict --description 'exit non-zero for improperly formatted checksum lines.'
complete -c gsha384sum -s w -l warn --description 'warn about improperly formatted checksum lines.'
complete -c gsha384sum -l help --description 'display this help and exit.'
complete -c gsha384sum -l version --description 'output version information and exit.'

