# gshred
# Autogenerated from man page /usr/local/share/man/man1/gshred.1
# using Deroffing man parser
complete -c gshred -s f -l force --description 'change permissions to allow writing if necessary.'
complete -c gshred -s n -l iterations --description 'overwrite N times instead of the default (3).'
complete -c gshred -l random-source --description 'get random bytes from FILE.'
complete -c gshred -s s -l size --description 'shred this many bytes (suffixes like K, M, G accepted).'
complete -c gshred -s u --description 'truncate and remove file after overwriting.'
complete -c gshred -l 'remove[' --description 'like -u but give control on HOW to delete;  See below.'
complete -c gshred -s v -l verbose --description 'show progress.'
complete -c gshred -s x -l exact --description 'do not round file sizes up to the next full blo… [See Man Page]'
complete -c gshred -s z -l zero --description 'add a final overwrite with zeros to hide shredding.'
complete -c gshred -l help --description 'display this help and exit.'
complete -c gshred -l version --description 'output version information and exit.'

