# gshuf
# Autogenerated from man page /usr/local/share/man/man1/gshuf.1
# using Deroffing man parser
complete -c gshuf -s e -l echo --description 'treat each ARG as an input line.'
complete -c gshuf -s i -l input-range --description 'treat each number LO through HI as an input line.'
complete -c gshuf -s n -l head-count --description 'output at most COUNT lines.'
complete -c gshuf -s o -l output --description 'write result to FILE instead of standard output.'
complete -c gshuf -l random-source --description 'get random bytes from FILE.'
complete -c gshuf -s r -l repeat --description 'output lines can be repeated.'
complete -c gshuf -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c gshuf -l help --description 'display this help and exit.'
complete -c gshuf -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

