# gsleep
# Autogenerated from man page /usr/local/share/man/man1/gsleep.1
# using Deroffing man parser
complete -c gsleep -l help --description 'display this help and exit.'
complete -c gsleep -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

