# gstat
# Autogenerated from man page /usr/local/share/man/man1/gstat.1
# using Deroffing man parser
complete -c gstat -s L -l dereference --description 'follow links.'
complete -c gstat -s f -l file-system --description 'display file system status instead of file status.'
complete -c gstat -s c -l format --description 'use the specified FORMAT instead of the default… [See Man Page]'
complete -c gstat -l printf --description 'like --format, but interpret backslash escapes,… [See Man Page]'
complete -c gstat -s t -l terse --description 'print the information in terse form.'
complete -c gstat -l help --description 'display this help and exit.'
complete -c gstat -l version --description 'output version information and exit .'

