# gstdbuf
# Autogenerated from man page /usr/local/share/man/man1/gstdbuf.1
# using Deroffing man parser
complete -c gstdbuf -s i -l input --description 'adjust standard input stream buffering.'
complete -c gstdbuf -s o -l output --description 'adjust standard output stream buffering.'
complete -c gstdbuf -s e -l error --description 'adjust standard error stream buffering.'
complete -c gstdbuf -l help --description 'display this help and exit.'
complete -c gstdbuf -l version --description 'output version information and exit.'

