# gstty
# Autogenerated from man page /usr/local/share/man/man1/gstty.1
# using Deroffing man parser
complete -c gstty -s a -l all --description 'print all current settings in human-readable form.'
complete -c gstty -s g -l save --description 'print all current settings in a stty-readable form.'
complete -c gstty -s F -l file --description 'open and use the specified DEVICE instead of stdin.'
complete -c gstty -l help --description 'display this help and exit.'
complete -c gstty -l version --description 'output version information and exit .'
complete -c gstty -o tabs --description 'same as tab3.'
complete -c gstty -o crtkill --description 'kill all line by obeying the echoctl and echok settings.'
complete -c gstty -o cbreak --description 'same as icanon.'
complete -c gstty -o cooked --description 'same as raw.'
complete -c gstty -o evenp --description 'same as -parenb cs8.'
complete -c gstty -o litout --description 'same as parenb istrip opost cs7.'
complete -c gstty -o nl --description 'same as icrnl -inlcr -igncr onlcr -ocrnl -onlret.'
complete -c gstty -o oddp --description 'same as -parenb cs8.'
complete -c gstty -o pass8 --description 'same as parenb istrip cs7.'
complete -c gstty -o raw --description 'same as cooked.'
complete -c gstty -o inlcr -o igncr -o icrnl -o ixon -o ixoff -o icanon -o opost --description '.'
complete -c gstty -o isig -o ixany -o imaxbel --description '.'
complete -c gstty -o iutf8 -o ocrnl --description 'opost -ofill onlcr -onocr -onlret nl0 cr0 tab0 … [See Man Page]'

