# gsum
# Autogenerated from man page /usr/local/share/man/man1/gsum.1
# using Deroffing man parser
complete -c gsum -s r --description 'use BSD sum algorithm, use 1K blocks.'
complete -c gsum -s s -l sysv --description 'use System V sum algorithm, use 512 bytes blocks.'
complete -c gsum -l help --description 'display this help and exit.'
complete -c gsum -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

