# gsync
# Autogenerated from man page /usr/local/share/man/man1/gsync.1
# using Deroffing man parser
complete -c gsync -s d -l data --description 'sync only file data, no unneeded metadata.'
complete -c gsync -s f -l file-system --description 'sync the file systems that contain the files.'
complete -c gsync -l help --description 'display this help and exit.'
complete -c gsync -l version --description 'output version information and exit.'

