# gtac
# Autogenerated from man page /usr/local/share/man/man1/gtac.1
# using Deroffing man parser
complete -c gtac -s b -l before --description 'attach the separator before instead of after.'
complete -c gtac -s r -l regex --description 'interpret the separator as a regular expression.'
complete -c gtac -s s -l separator --description 'use STRING as the separator instead of newline.'
complete -c gtac -l help --description 'display this help and exit.'
complete -c gtac -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

