# gtags
# Autogenerated from man page /usr/local/share/man/man1/gtags.1
# using Deroffing man parser
complete -c gtags -l accept-dotfiles --description 'Accept files and directories whose names begin with a dot.'
complete -c gtags -s c -l compact --description 'Make \'GTAGS\' in compact format.'
complete -c gtags -l 'config[' --description 'Print the value of config variable name.'
complete -c gtags -s d -l dump --description 'Dump a tag file as text to the standard output.'
complete -c gtags -l explain --description 'Explain handling files.'
complete -c gtags -s f -l file --description 'Give a list of candidates of target files.'
complete -c gtags -l gtagsconf --description 'Set environment variable GTAGSCONF to file.'
complete -c gtags -l gtagslabel --description 'Set environment variable GTAGSLABEL to label.'
complete -c gtags -s I -l idutils --description 'In addition to tag files, make ID database for idutils(1).'
complete -c gtags -s i -l incremental --description 'Update tag files incrementally.'
complete -c gtags -s O -l objdir --description 'Use BSD-style objdir as the location of tag files.'
complete -c gtags -l single-update --description 'Update tag files for a single file.'
complete -c gtags -l skip-unreadable --description 'Skip unreadable files.'
complete -c gtags -l sqlite3 --description 'Use Sqlite 3 API to make tag files.  By default, BSD/DB 1.'
complete -c gtags -l statistics --description 'Print statistics information.'
complete -c gtags -s q -l quiet --description 'Quiet mode.'
complete -c gtags -s v -l verbose --description 'Verbose mode.'
complete -c gtags -s w -l warning --description 'Print warning messages.'
complete -c gtags -l with-sqlite3 --description '.'

