# gtags-cscope
# Autogenerated from man page /usr/local/share/man/man1/gtags-cscope.1
# using Deroffing man parser
complete -c gtags-cscope -s h --description 'View the long usage help display.'
complete -c gtags-cscope -s V --description 'Print the version number of gtags-cscope.'
complete -c gtags-cscope -l help --description 'Same as -h.'
complete -c gtags-cscope -l version --description 'Same as -V .'
complete -c gtags-cscope -s a --description 'Print absolute path names.'
complete -c gtags-cscope -s b --description 'Build the cross-reference only.'
complete -c gtags-cscope -s C --description 'Ignore letter case when searching.'
complete -c gtags-cscope -s d --description 'Do not update the cross-reference.'
complete -c gtags-cscope -s e --description 'Suppress the \'^e\' command prompt between files.'
complete -c gtags-cscope -s F --description 'Read symbol reference lines from file.'
complete -c gtags-cscope -s i --description 'Ignore SIGINT signal in line-oriented mode.'
complete -c gtags-cscope -s L --description 'Do a single search with line-oriented output wh… [See Man Page]'
complete -c gtags-cscope -s l --description 'Line-oriented interface.  This option implies the -d option.'
complete -c gtags-cscope -o '[0-9]' --description 'Go to input field num (counting from 0) and find pattern.'
complete -c gtags-cscope -s p --description 'Display the last n file path components instead… [See Man Page]'
complete -c gtags-cscope -o num --description '.'
complete -c gtags-cscope -s v --description 'Be more verbose in line-oriented mode.'

