# gtail
# Autogenerated from man page /usr/local/share/man/man1/gtail.1
# using Deroffing man parser
complete -c gtail -s c -l bytes --description 'output the last NUM bytes; or use -c +NUM to ou… [See Man Page]'
complete -c gtail -s f -l 'follow[' --description 'output appended data as the file grows; P an ab… [See Man Page]'
complete -c gtail -s F --description 'same as --follow=\\,name\\/ --retry.'
complete -c gtail -s n -l lines --description 'output the last NUM lines, instead of the last … [See Man Page]'
complete -c gtail -l max-unchanged-stats --description 'with --follow=\\,name\\/, reopen a FILE which has… [See Man Page]'
complete -c gtail -l pid --description 'with -f, terminate after process ID, PID dies.'
complete -c gtail -s q -l quiet -l silent --description 'never output headers giving file names.'
complete -c gtail -l retry --description 'keep trying to open a file if it is inaccessible.'
complete -c gtail -s s -l sleep-interval --description 'with -f, sleep for approximately N seconds (default 1.'
complete -c gtail -s v -l verbose --description 'always output headers giving file names.'
complete -c gtail -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c gtail -l help --description 'display this help and exit.'
complete -c gtail -l version --description 'output version information and exit.'

