# gtee
# Autogenerated from man page /usr/local/share/man/man1/gtee.1
# using Deroffing man parser
complete -c gtee -s a -l append --description 'append to the given FILEs, do not overwrite.'
complete -c gtee -s i -l ignore-interrupts --description 'ignore interrupt signals.'
complete -c gtee -s p --description 'diagnose errors writing to non pipes.'
complete -c gtee -l 'output-error[' --description 'set behavior on write error.   See MODE below.'
complete -c gtee -l help --description 'display this help and exit.'
complete -c gtee -l version --description 'output version information and exit .'

