# gtimeout
# Autogenerated from man page /usr/local/share/man/man1/gtimeout.1
# using Deroffing man parser
complete -c gtimeout -l help --description 'display this help and exit.'
complete -c gtimeout -l preserve-status --description 'exit with the same status as COMMAND, even when… [See Man Page]'
complete -c gtimeout -l foreground --description 'when not running timeout directly from a shell … [See Man Page]'
complete -c gtimeout -s k -l kill-after --description 'also send a KILL signal if COMMAND is still run… [See Man Page]'
complete -c gtimeout -s s -l signal --description 'specify the signal to be sent on timeout; SIGNA… [See Man Page]'
complete -c gtimeout -l version --description 'output version information and exit.'

