# gtouch
# Autogenerated from man page /usr/local/share/man/man1/gtouch.1
# using Deroffing man parser
complete -c gtouch -s a --description 'change only the access time.'
complete -c gtouch -s c -l no-create --description 'do not create any files.'
complete -c gtouch -s d -l date --description 'parse STRING and use it instead of current time.'
complete -c gtouch -s f --description '(ignored).'
complete -c gtouch -s h -l no-dereference --description 'affect each symbolic link instead of any refere… [See Man Page]'
complete -c gtouch -s m --description 'change only the modification time.'
complete -c gtouch -s r -l reference --description 'use this file\'s times instead of current time.'
complete -c gtouch -s t --description 'use [[CC]YY]MMDDhhmm[. ss] instead of current time.'
complete -c gtouch -l time --description 'change the specified time: WORD is access, atim… [See Man Page]'
complete -c gtouch -l help --description 'display this help and exit.'
complete -c gtouch -l version --description 'output version information and exit.'

