# gtr
# Autogenerated from man page /usr/local/share/man/man1/gtr.1
# using Deroffing man parser
complete -c gtr -s c -s C -l complement --description 'use the complement of SET1.'
complete -c gtr -s d -l delete --description 'delete characters in SET1, do not translate.'
complete -c gtr -s s -l squeeze-repeats --description 'replace each sequence of a repeated character t… [See Man Page]'
complete -c gtr -s t -l truncate-set1 --description 'first truncate SET1 to length of SET2.'
complete -c gtr -l help --description 'display this help and exit.'
complete -c gtr -l version --description 'output version information and exit .'

