# gtruncate
# Autogenerated from man page /usr/local/share/man/man1/gtruncate.1
# using Deroffing man parser
complete -c gtruncate -s c -l no-create --description 'do not create any files.'
complete -c gtruncate -s o -l io-blocks --description 'treat SIZE as number of IO blocks instead of bytes.'
complete -c gtruncate -s r -l reference --description 'base size on RFILE.'
complete -c gtruncate -s s -l size --description 'set or adjust the file size by SIZE bytes.'
complete -c gtruncate -l help --description 'display this help and exit.'
complete -c gtruncate -l version --description 'output version information and exit.'

