# gtrue
# Autogenerated from man page /usr/local/share/man/man1/gtrue.1
# using Deroffing man parser
complete -c gtrue -l help --description 'display this help and exit.'
complete -c gtrue -l version --description 'output version information and exit.'

