# guname
# Autogenerated from man page /usr/local/share/man/man1/guname.1
# using Deroffing man parser
complete -c guname -s a -l all --description 'print all information, in the following order, … [See Man Page]'
complete -c guname -s s -l kernel-name --description 'print the kernel name.'
complete -c guname -s n -l nodename --description 'print the network node hostname.'
complete -c guname -s r -l kernel-release --description 'print the kernel release.'
complete -c guname -s v -l kernel-version --description 'print the kernel version.'
complete -c guname -s m -l machine --description 'print the machine hardware name.'
complete -c guname -s p -l processor --description 'print the processor type (non-portable).'
complete -c guname -s i -l hardware-platform --description 'print the hardware platform (non-portable).'
complete -c guname -s o -l operating-system --description 'print the operating system.'
complete -c guname -l help --description 'display this help and exit.'
complete -c guname -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

