# gunexpand
# Autogenerated from man page /usr/local/share/man/man1/gunexpand.1
# using Deroffing man parser
complete -c gunexpand -s a -l all --description 'convert all blanks, instead of just initial blanks.'
complete -c gunexpand -l first-only --description 'convert only leading sequences of blanks (overrides -a).'
complete -c gunexpand -s t -l tabs --description 'have tabs N characters apart instead of 8 (enables -a).'
complete -c gunexpand -l help --description 'display this help and exit.'
complete -c gunexpand -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

