# guniq
# Autogenerated from man page /usr/local/share/man/man1/guniq.1
# using Deroffing man parser
complete -c guniq -s c -l count --description 'prefix lines by the number of occurrences.'
complete -c guniq -s d -l repeated --description 'only print duplicate lines, one for each group.'
complete -c guniq -s D --description 'print all duplicate lines.'
complete -c guniq -l 'all-repeated[' --description 'like -D, but allow separating groups with an em… [See Man Page]'
complete -c guniq -s f -l skip-fields --description 'avoid comparing the first N fields.'
complete -c guniq -l 'group[' --description 'show all items, separating groups with an empty… [See Man Page]'
complete -c guniq -s i -l ignore-case --description 'ignore differences in case when comparing.'
complete -c guniq -s s -l skip-chars --description 'avoid comparing the first N characters.'
complete -c guniq -s u -l unique --description 'only print unique lines.'
complete -c guniq -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c guniq -s w -l check-chars --description 'compare no more than N characters in lines.'
complete -c guniq -l help --description 'display this help and exit.'
complete -c guniq -l version --description 'output version information and exit.'

