# gusers
# Autogenerated from man page /usr/local/share/man/man1/gusers.1
# using Deroffing man parser
complete -c gusers -l help --description 'display this help and exit.'
complete -c gusers -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

