# gwhoami
# Autogenerated from man page /usr/local/share/man/man1/gwhoami.1
# using Deroffing man parser
complete -c gwhoami -l help --description 'display this help and exit.'
complete -c gwhoami -l version --description 'output version information and exit AUTHOR Writ… [See Man Page]'

