# gwho
# Autogenerated from man page /usr/local/share/man/man1/gwho.1
# using Deroffing man parser
complete -c gwho -s a -l all --description 'same as -b -d --login -p -r -t -T -u.'
complete -c gwho -s b -l boot --description 'time of last system boot.'
complete -c gwho -s d -l dead --description 'print dead processes.'
complete -c gwho -s H -l heading --description 'print line of column headings.'
complete -c gwho -s l -l login --description 'print system login processes.'
complete -c gwho -l lookup --description 'attempt to canonicalize hostnames via DNS.'
complete -c gwho -s m --description 'only hostname and user associated with stdin.'
complete -c gwho -s p -l process --description 'print active processes spawned by init.'
complete -c gwho -s q -l count --description 'all login names and number of users logged on.'
complete -c gwho -s r -l runlevel --description 'print current runlevel.'
complete -c gwho -s s -l short --description 'print only name, line, and time (default).'
complete -c gwho -s t -l time --description 'print last system clock change.'
complete -c gwho -s T -s w -l mesg --description 'add user\'s message status as +, - or ?.'
complete -c gwho -s u -l users --description 'list users logged in.'
complete -c gwho -l message --description 'same as -T.'
complete -c gwho -l writable --description 'same as -T.'
complete -c gwho -l help --description 'display this help and exit.'
complete -c gwho -l version --description 'output version information and exit.'

