# htags-server
# Autogenerated from man page /usr/local/share/man/man1/htags-server.1
# using Deroffing man parser
complete -c htags-server -s b -l bind --description 'Specifies the IP address on which htags-server listen.'
complete -c htags-server -s u -l use --description 'Specifies language to use, which may be one of:… [See Man Page]'

