# icns2png
# Autogenerated from man page /usr/local/share/man/man1/icns2png.1
# using Deroffing man parser
complete -c icns2png -s l -l list --description 'List the contents of one or more icns images .'
complete -c icns2png -s o -l output --description 'Where to place extracted files.'
complete -c icns2png -s d -l depth --description 'Sets the pixel depth of the icons to extract.  (1,4,8,32).'
complete -c icns2png -s s -l size --description 'Sets the width and height of the icons to extract.'
complete -c icns2png -s x -l extract --description '.'
complete -c icns2png -s h -l help --description 'Displays this help message.'
complete -c icns2png -s v -l version --description 'EXAMPLES icns2png -x anicon.'

