# layerutil
# Autogenerated from man page /usr/share/man/man1/layerutil.1
# using Darwin man parser
complete -c layerutil -s c --description 'Convert to lcr format.'
complete -c layerutil -s l --description 'Set the lossy compression factor used for image… [See Man Page]'
complete -c layerutil -s o --description 'Output file name.'
complete -c layerutil -s h --description 'Prints out usage information.'
complete -c layerutil -s V --description 'Prints out version information.  \\" Ends the list Pp.'

