# level
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/level.1
# using Deroffing man parser
complete -c level -s l --description 'Just list the level on a line by itself.   Useful for scripts.'

