# lskq
# Autogenerated from man page /usr/share/man/man1/lskq.1
# using Darwin man parser
complete -c lskq -s p --description 'Show kqueues of process <pid>.'
complete -c lskq -s a --description 'Show kqueues for all running processes.  Requires root.'
complete -c lskq -s v --description 'Verbose: show opaque user data and filter-speci… [See Man Page]'
complete -c lskq -s e --description 'Ignore empty kqueues.'
complete -c lskq -s h --description 'Show help and exit.'

