# lua-5
# Autogenerated from man page /usr/local/share/man/man1/lua-5.1.1
# using Deroffing man parser
complete -c lua-5 -s e --description 'execute statement R stat .'
complete -c lua-5 -s i --description 'enter interactive mode after  script is executed.'
complete -c lua-5 -s l --description 'call  require(\' name \') before executing R script .'
complete -c lua-5 -s v --description 'is assumed when the standard input is a terminal; otherwise,.'

