# makepatch
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/makepatch.1
# using Deroffing man parser
complete -c makepatch -s B --description 'Include the data from any BAM files in the patch.'
complete -c makepatch -s C --description 'Generate a patch compatible with any supported versions of .'
complete -c makepatch -s d --description 'Add a header with the unified diffs to the top of the  patch.'
complete -c makepatch -s v --description 'Be more verbose for each instance.'

