# mDNSResponder
# Autogenerated from man page /usr/share/man/man8/mDNSResponder.8
# using Darwin man parser
complete -c mDNSResponder -o AlwaysAppendSearchDomains --description 'Append search domains for multi-labeled Partial… [See Man Page]'
complete -c mDNSResponder -o NoMulticastAdvertisements --description 'Prevent the system from advertising Bonjour ser… [See Man Page]'

