# merge
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/merge.1
# using Deroffing man parser
complete -c merge -s s --description 'Perform a set merge instead of a normal file merge.'

