# mv
# Autogenerated from man page /usr/share/man/man1/mv.1
# using Darwin man parser
complete -c mv -s i --description 'Cause mv mv to write a prompt to standard error… [See Man Page]'
complete -c mv -s n --description 'Do not overwrite an existing file.'
complete -c mv -s v --description 'Cause mv mv to be verbose, showing files after they are moved.'

