# names
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/names.1
# using Deroffing man parser
complete -c names -s q --description 'Quiet mode.  CATEGORY Utility.'

