# ncctl
# Autogenerated from man page /usr/share/man/man1/ncctl.1
# using Darwin man parser
complete -c ncctl -s h --description 'Print a help summary of the command and then exit.'
complete -c ncctl -s v --description 'Be verbose and show what file system is being o… [See Man Page]'
complete -c ncctl -s P --description 'If the trailing component resolves to a symboli… [See Man Page]'
complete -c ncctl -s p --description 'For the init, set and ncctl ncinit commands set… [See Man Page]'
complete -c ncctl -s F --description 'For the init, set and ncctl ncinit commands to … [See Man Page]'

