# ncdestroy
# Autogenerated from man page /usr/share/man/man1/ncdestroy.1
# using Darwin man parser
complete -c ncdestroy -s h --description 'Print a help summary of the command and then exit.'
complete -c ncdestroy -s v --description 'Be verbose and show what file system is being o… [See Man Page]'
complete -c ncdestroy -s P --description 'If the trailing component resolves to a symboli… [See Man Page]'
complete -c ncdestroy -s p --description 'For the init, set and ncdestroy ncinit commands… [See Man Page]'
complete -c ncdestroy -s F --description 'For the init, set and ncdestroy ncinit commands… [See Man Page]'

