# ncinit
# Autogenerated from man page /usr/share/man/man1/ncinit.1
# using Darwin man parser
complete -c ncinit -s h --description 'Print a help summary of the command and then exit.'
complete -c ncinit -s v --description 'Be verbose and show what file system is being o… [See Man Page]'
complete -c ncinit -s P --description 'If the trailing component resolves to a symboli… [See Man Page]'
complete -c ncinit -s p --description 'For the init, set and ncinit ncinit commands se… [See Man Page]'
complete -c ncinit -s F --description 'For the init, set and ncinit ncinit commands to… [See Man Page]'

