# nclist
# Autogenerated from man page /usr/share/man/man1/nclist.1
# using Darwin man parser
complete -c nclist -s h --description 'Print a help summary of the command and then exit.'
complete -c nclist -s v --description 'Be verbose and show what file system is being o… [See Man Page]'
complete -c nclist -s P --description 'If the trailing component resolves to a symboli… [See Man Page]'
complete -c nclist -s p --description 'For the init, set and nclist ncinit commands se… [See Man Page]'
complete -c nclist -s F --description 'For the init, set and nclist ncinit commands to… [See Man Page]'

