# new
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/new.1
# using Deroffing man parser
complete -c new -s b --description 'force binary encoding with no keyword expansion… [See Man Page]'
complete -c new -s c --description 'Use comments saved by a previous run of citool,… [See Man Page]'
complete -c new -s q --description 'be quiet.  SEE ALSO CATEGORY File.'

