# node
# Autogenerated from man page /usr/local/share/man/man1/node.1
# using Deroffing man parser
complete -c node -s v -l version --description 'Print node\'s version.'
complete -c node -s h -l help --description 'Print node command line options.'
complete -c node -s e -l eval --description 'Evaluate the following argument as JavaScript.'
complete -c node -s p -l print --description 'Identical to -e but prints the result.'
complete -c node -s c -l check --description 'Syntax check the script without executing.'
complete -c node -s i -l interactive --description 'Opens the REPL even if stdin does not appear to be a terminal.'
complete -c node -s r -l require --description 'Preload the specified module at startup.'
complete -c node -l no-deprecation --description 'Silence deprecation warnings.'
complete -c node -l trace-deprecation --description 'Print stack traces for deprecations.'
complete -c node -l throw-deprecation --description 'Throw errors for deprecations.'
complete -c node -l trace-sync-io --description 'Prints a stack trace whenever synchronous I/O i… [See Man Page]'
complete -c node -l track-heap-objects --description 'Track heap object allocations for heap snapshots.'
complete -c node -l zero-fill-buffers --description 'Automatically zero-fills all newly allocated Bu… [See Man Page]'
complete -c node -l prof-process --description 'Process v8 profiler output generated using the … [See Man Page]'
complete -c node -l v8-options --description 'Print v8 command line options.'
complete -c node -l v8-pool-size --description 'Set v8\'s thread pool size which will be used to… [See Man Page]'
complete -c node -l tls-cipher-list --description 'Specify an alternative default TLS cipher list.'
complete -c node -l enable-fips --description 'Enable FIPS-compliant crypto at startup.  (Requires Node.'
complete -c node -l force-fips --description 'Force FIPS-compliant crypto on startup.'
complete -c node -l icu-data-dir --description 'Specify ICU data load path.  (overrides NODE_ICU_DATA).'

