# ntpd
# Autogenerated from man page /usr/share/man/man8/ntpd.8
# using Darwin man parser
complete -c ntpd -s m --description 'Synchronize using NTP multicast messages on the… [See Man Page]'
complete -c ntpd -s v --description '.'
complete -c ntpd -s V --description 'Add a system variable listed by default.'

