# ocamlcp
# Autogenerated from man page /usr/local/share/man/man1/ocamlcp.1
# using Deroffing man parser
complete -c ocamlcp -o pp --description 'option is not supported.'
complete -c ocamlcp -s P --description 'option.'
complete -c ocamlcp -s p --description 'with the same argument and meaning as.'

