# ostraceutil
# Autogenerated from man page /usr/share/man/man1/ostraceutil.1
# using Darwin man parser
complete -c ostraceutil -o activity --description 'Stream will filter a specific activity from a p… [See Man Page]'
complete -c ostraceutil -o buffered --description 'Stream will run in buffered mode (delivers as b… [See Man Page]'
complete -c ostraceutil -o errors --description 'Watch for software errors triggered by processes.'
complete -c ostraceutil -o faults --description 'Watch for software faults triggered by processes.'
complete -c ostraceutil -o filter --description 'Stream will filter messages based on the provid… [See Man Page]'
complete -c ostraceutil -o list --description 'Will list all available trace related strings for a binary.'
complete -c ostraceutil -o payload --description 'Will output the payload content, forcing the output to be JSON.'
complete -c ostraceutil -o parent --description 'When passed with stream any processes that are … [See Man Page]'
complete -c ostraceutil -o process --description 'The process to operate on.'
complete -c ostraceutil -o setmode --description 'Changes the mode of a process.'
complete -c ostraceutil -o timeout --description 'Timeout a stream or watch operation after a spe… [See Man Page]'
complete -c ostraceutil -o source --description 'Include symbol names and source line numbers for stream.'
complete -c ostraceutil -o stream --description 'Stream breadcrumbs, activities and/or trace mes… [See Man Page]'
complete -c ostraceutil -o type --description 'Dictates the type of events to stream from a process.'
complete -c ostraceutil -o quiet --description 'Reduce the amount of duplicate information in o… [See Man Page]'
complete -c ostraceutil -o watch --description 'Watch for events for a given process or all processes.'

