# parent
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/parent.1
# using Deroffing man parser
complete -c parent -s 1 --description 'List only the first parent found.    May be combined with.'
complete -c parent -s a --description 'Add the specified parent pointer to the list of parents.'
complete -c parent -s i --description 'Operate only on incoming (pull) parent pointers.'
complete -c parent -s l --description 'List the parent pointer[s] without any annotati… [See Man Page]'
complete -c parent -s o --description 'Operate only on outgoing (push) parent pointers.'
complete -c parent -s q --description 'Do not produce output when adding/removing/listing parents.'
complete -c parent -s r --description 'Remove the parent pointer.  May be combined with.'
complete -c parent -s s --description 'Set the parent pointer[s] to the specified list… [See Man Page]'

