# patch
# Autogenerated from man page /usr/share/man/man1/patch.1
# using Deroffing man parser
complete -c patch -l 'option.' --description 'The names of the files to be patched are usuall… [See Man Page]'
complete -c patch -l option --description '.'
complete -c patch -s p --description 'or.'
complete -c patch -l 'option)' --description 'but an RCS, ClearCase, Perforce, or SCCS master… [See Man Page]'
complete -c patch -o p0 --description 'gives the entire file name unmodified,.'
complete -c patch -o p1 --description 'gives.'
complete -c patch -o p4 --description 'gives.'
complete -c patch -l -Y --description 'or.'
complete -c patch -l and --description '.'
complete -c patch -l options --description 'If none of these options are given, then a simp… [See Man Page]'
complete -c patch -o Np1 --description 'is recommended.'
complete -c patch -o 'p0.' --description 'The.'

