# pending
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/pending.1
# using Deroffing man parser
complete -c pending -s S --description '.'
complete -c pending -l standalone --description 'Limit the list to the current component.'
complete -c pending -s q --description 'No output.'

