# prompt
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/prompt.1
# using Deroffing man parser
complete -c prompt -s c --description 'Only for command line prompts, print the message and exit 0.'
complete -c prompt -s e --description 'Indicates that the prompt is an error message.'
complete -c prompt -s p --description 'option is present, the last command line argume… [See Man Page]'
complete -c prompt -s g --description 'Override the .'
complete -c prompt -s i --description 'Indicates that the prompt is an informational message.'
complete -c prompt -s o --description 'OK only, clears the default "Not used in command line context.'
complete -c prompt -s w --description 'Indicates that the prompt is a warning message.'

