# pstree
# Autogenerated from man page /usr/local/share/man/man1/pstree.1
# using Darwin man parser
complete -c pstree -s f --description 'Read input from file instead of running ps -kax… [See Man Page]'
complete -c pstree -s g --description 'Use graphics chars for tree.'
complete -c pstree -s l --description 'Show a maximum of n levels.'
complete -c pstree -s p --description 'Show only parents and descendants of the process pid.'
complete -c pstree -s s --description 'Show only parents and descendants of processes … [See Man Page]'
complete -c pstree -s U --description 'Do not show branches containing only root processes.'
complete -c pstree -s u --description 'Show only parents and descendants of processes of user.'
complete -c pstree -s w --description 'Wide output, not truncated to terminal width.'

