# r2c
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/r2c.1
# using Deroffing man parser
complete -c r2c -s S --description '.'
complete -c r2c -l standalone --description 'If run in a component of a nested collection, c… [See Man Page]'

