# reaver
# Autogenerated from man page /usr/local/share/man/man1/reaver.1.gz
# using Deroffing man parser
complete -c reaver -s m -l mac --description '.'
complete -c reaver -s e -l essid --description '.'
complete -c reaver -s c -l channel --description '.'
complete -c reaver -s o -l out-file --description '.'
complete -c reaver -s f -l fixed --description '.'
complete -c reaver -s 5 -l 5ghz --description '.'
complete -c reaver -s v -l verbose --description '.'
complete -c reaver -s q -l quiet --description '.'
complete -c reaver -s i -l interface --description '.'
complete -c reaver -s b -l bssid --description '.'
complete -c reaver -s p -l pin --description '.'
complete -c reaver -s h -l help --description '.'

