# receive
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/receive.1
# using Deroffing man parser
complete -c receive -s i --description 'option.   does not create repositories by default.'
complete -c receive -o vv --description 'to the options.'
complete -c receive -s a --description 'Apply the changes (call  bk resolve . ).'
complete -c receive -s c --description 'Do not accept conflicts with this patch.'
complete -c receive -s v --description 'Verbose level, more is more verbose,.'

