# renumber
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/renumber.1
# using Deroffing man parser
complete -c renumber -s n --description 'do not do anything, dry run.'
complete -c renumber -s q --description 'be quiet.  CATEGORY Utility.'

