# repotype
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/repotype.1
# using Deroffing man parser
complete -c repotype -s q --description 'the exit status is 0 for all valid repositories… [See Man Page]'

