# repos
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/repos.1
# using Deroffing man parser
complete -c repos -l check-all --description 'Validate that all the saved repository location… [See Man Page]'
complete -c repos -s q --description 'Allow the list to be updated but do not output anything.'
complete -c repos -l raw --description 'Output the list of repository locations without… [See Man Page]'
complete -c repos -s a --description 'Sort the output on access time.'
complete -c repos -s m --description 'Sort the output on modification time.'
complete -c repos -s v --description 'Output all of the data associated with each repository.'

