# repocheck
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/repocheck.1
# using Deroffing man parser
complete -c repocheck -l check-opts -o 'e\'' --description '.'
complete -c repocheck -s q --description 'Run quietly.'
complete -c repocheck -s S --description 'Just check the current repo.'

