# resolve
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/resolve.1
# using Deroffing man parser
complete -c resolve -s a --description 'Automerge.'
complete -c resolve -s A --description 'Auto advance.'
complete -c resolve -s c --description 'No conflicts.'
complete -c resolve -s q --description 'Be quiet.'
complete -c resolve -s r --description 'Re-merge.'
complete -c resolve -l batch --description 'do not do interactive resolve of any conflicts,… [See Man Page]'
complete -c resolve -s T --description 'Text-only.'

