# root
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/root.1
# using Deroffing man parser
complete -c root -s S --description 'option.  CATEGORY Admin.'

