# rset
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/rset.1
# using Deroffing man parser
complete -c rset -s a --description 'Show deleted files which are normally suppressed.'
complete -c rset -s h --description 'Show the "This makes the output look like.'
complete -c rset -o sHERE --description '.'
complete -c rset -s S --description '.'
complete -c rset -l standalone --description 'Just run rset on the current component.'
complete -c rset -s U --description 'User files only (like bk -U).'

