# sane-config
# Autogenerated from man page /usr/local/share/man/man1/sane-config.1
# using Deroffing man parser
complete -c sane-config -l version --description 'Print the currently installed version of libsan… [See Man Page]'
complete -c sane-config -l help --description 'Print a short usage message.'
complete -c sane-config -l libs --description 'Print the additional libraries that are necessa… [See Man Page]'
complete -c sane-config -l ldflags --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c sane-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c sane-config -l prefix --description 'Print the prefix used during compilation of libsane.'
complete -c sane-config -l exec-prefix --description 'Print the exec-prefix used during compilation of libsane.'

