# script
# Autogenerated from man page /usr/share/man/man1/script.1
# using Darwin man parser
complete -c script -s a --description 'Append the output to file or typescript, retain… [See Man Page]'
complete -c script -s d --description 'When playing back a session with the p flag, do… [See Man Page]'
complete -c script -s F --description 'Immediately flush output after each write.'
complete -c script -s k --description 'Log keys sent to the program as well as output.'
complete -c script -s p --description 'Play back a session recorded with the r flag in real time.'
complete -c script -s q --description 'Run in quiet mode, omit the start, stop and com… [See Man Page]'
complete -c script -s r --description 'Record a session with input, output, and timestamping.'
complete -c script -s t --description 'Specify the interval at which the script output… [See Man Page]'

