# superset
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/superset.1
# using Deroffing man parser
complete -c superset -s q --description 'Be quiet EXIT STATUS bk superset returns exit status.'

