# unbound
# Autogenerated from man page /usr/share/man/man8/unbound.8
# using Deroffing man parser
complete -c unbound -s h --description 'Show the version and commandline option help.'
complete -c unbound -s c --description 'Set the config file with settings for unbound t… [See Man Page]'
complete -c unbound -s d --description 'Debug flag: do not fork into the background, bu… [See Man Page]'
complete -c unbound -s v --description 'Increase verbosity.'

