# undo
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/undo.1
# using Deroffing man parser
complete -c undo -s f --description 'Force the undo to complete if it can.'
complete -c undo -l force-unpopulate --description 'If the undo results in a component being remove… [See Man Page]'
complete -c undo -s q --description 'Run quietly; do not list files.'
complete -c undo -s S --description '.'
complete -c undo -l standalone --description 'Just undo the current component.'
complete -c undo -s s --description 'Do not save undone changes as a patch.'
complete -c undo -s v --description 'When prompting with the list of changes to be u… [See Man Page]'

