# uninstall
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/uninstall.1
# using Deroffing man parser
complete -c uninstall -s f --description 'Force uninstallation; do not prompt.  SEE ALSO.'

