# unlock
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/unlock.1
# using Deroffing man parser
complete -c unlock -s r --description 'Remove all read locks, stale or not.'
complete -c unlock -s s --description 'Remove both read and write locks, but only if they are stale.'
complete -c unlock -s w --description 'Remove the write lock, stale or not.'

