# unpull
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/unpull.1
# using Deroffing man parser
complete -c unpull -s f --description 'Force unpull.'
complete -c unpull -s q --description 'Quiet mode.'
complete -c unpull -s S --description '.'
complete -c unpull -l standalone --description 'In a nested collection this makes unpull operat… [See Man Page]'
complete -c unpull -s s --description 'Do not save a backup patch in BitKeeper/tmp/unpull. patch .'

