# upgrade
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/upgrade.1
# using Deroffing man parser
complete -c upgrade -s c --description 'Just check to see if a new version  is availabl… [See Man Page]'
complete -c upgrade -s d --description 'Download the installer for a new version of , b… [See Man Page]'
complete -c upgrade -s f --description 'If the bk upgrade command is unable to determin… [See Man Page]'
complete -c upgrade -s q --description 'This causes the upgrade program to suppress ext… [See Man Page]'

