# w3mman
# Autogenerated from man page /usr/local/share/man/man1/w3mman.1
# using Deroffing man parser
complete -c w3mman -s M --description 'Specify   path as MANPATH.'
complete -c w3mman -s k --description 'Specify   keyword.'
complete -c w3mman -s l --description 'Specify a   file.  ENVIRONMENT.'

