# wine
# Autogenerated from man page /usr/local/share/man/man1/wine.1
# using Deroffing man parser
complete -c wine -l help --description 'or.'
complete -c wine -l version --description 'as the only argument, wine will simply print a … [See Man Page]'

