# wineconsole
# Autogenerated from man page /usr/local/share/man/man1/wineconsole.1
# using Deroffing man parser
complete -c wineconsole -l backend --description 'If user is chosen, a new window will be created… [See Man Page]'

