# WirelessRadioManagerd
# Autogenerated from man page /usr/share/man/man1/WirelessRadioManagerd.1
# using Darwin man parser
complete -c WirelessRadioManagerd -s a --description 'Description of -a flag.'
complete -c WirelessRadioManagerd -s b --description 'Description of -b flag \\" Ends the list Pp .'

