# xfindproxy
# Autogenerated from man page /opt/X11/share/man/man1/xfindproxy.1
# using Deroffing man parser
complete -c xfindproxy -o manager --description 'argument is required, and it specifies the netw… [See Man Page]'
complete -c xfindproxy -o name --description 'argument is required, and it specifies the name… [See Man Page]'
complete -c xfindproxy -o server --description 'argument is also required, and it specifies the… [See Man Page]'
complete -c xfindproxy -o auth --description 'argument is optional.'
complete -c xfindproxy -o host --description 'argument is optional.'
complete -c xfindproxy -o options --description 'argument is optional.'
complete -c xfindproxy -o version --description 'argument prints the program version and exits.'

