# xflags
# Autogenerated from man page /Applications/BitKeeper.app/Contents/Resources/bitkeeper/man/man1/xflags.1
# using Deroffing man parser
complete -c xflags -s n --description 'Do not change any files, just list any problems found.'
complete -c xflags -s s --description 'Do not change any files, do not list any status… [See Man Page]'

