#!/bin/sh

pip2 install virtualenv
while read p pkg; do

    if [ ".$pkg" = "." ]; then
        pkg=$p
    fi

    virtualenv --no-site-packages $p
    (
    cd $p
    source ./bin/activate
    pip2 install $pkg
    deactivate
    )
done <<-END
pyinstaller
linters  autopep8 autoflake isort pyflakes
END
