---
last_check:
  etag: '"2c9775ffbbeec98794e3919cc606257e"'
  version: 1.8.10
  at: 1569223723
checked_completion: true
completion_version: 1.8.10
endpoints:
  https://api.travis-ci.org/:
    access_token: 
repos:
  openacid/slim:
    endpoint: https://api.travis-ci.org/
  openacid/low:
    endpoint: https://api.travis-ci.org/
  openacid/trie:
    endpoint: https://api.travis-ci.org/
