#!/bin/sh

# encryption edit

fn=$1
fn=${fn%.des3}.des3
[ -f "$fn" ] || touch $fn

if [ ".$SECPASS" = "." ]; then
    printf "enter des-ede3-cbc decryption password:"
    read -s SECPASS
fi

# -md md5 is required:
# https://unix.stackexchange.com/questions/606493/cannot-decrypt-files-on-a-mac-using-openssl
content="$(cat "$fn" | SECPASS="$SECPASS" openssl des3 -d  -md md5 -pass env:SECPASS)"

SECPASS="$SECPASS" CONTENT="$content" vim \
    -c 'put=$CONTENT' \
    -c 'file des3-b64://des3-content' \
    -c 'set buftype=acwrite' \
    -c 'au BufWriteCmd * exec "silent w !cat | openssl des3 -pass env:SECPASS > '"$fn"'"'
