#!/bin/sh

# encryption view

fn=$1
fn=${fn%.des3}.des3
[ -f "$fn" ] || touch $fn

if [ ".$SECPASS" = "." ]; then
    printf "enter des-ede3-cbc decryption password:"
    read -s SECPASS
fi

# -md md5 is required:
# https://unix.stackexchange.com/questions/606493/cannot-decrypt-files-on-a-mac-using-openssl
SECPASS="$SECPASS" openssl des3 -d  -md md5 -pass env:SECPASS -in $fn
