#!/bin/sh

# encryption view

fn=$1
fn=${fn%.des3}.des3
[ -f "$fn" ] || touch $fn

if [ ".$SECPASS" = "." ]; then
    printf "enter des-ede3-cbc decryption password:"
    read -s SECPASS
fi

SECPASS="$SECPASS" openssl des3 -d -pass env:SECPASS -in $fn
