#!/bin/bash

while [ $? -eq 0 ];do
    nc.traditional -vlp 8080 -c '(
    r=read
    e=echo

    $r a b c
    z=$r

    while [ ${#z} -gt 2 ]; do
        $r z
    done

    f=.`$e $b`
    echo $f >&2

    h="HTTP/1.0"
    o="$h 200 OK\r\n"
    c="Content"

    if [ -z $f ];then
        ( $e $o
        ls|(
        while $r n
        do
            if [ -f "$n" ]; then
                $e "`ls -gh $n`"
            fi
        done
        )
        )
    elif [ -f $f ];then
        case $f in
            *.js)
                t=application/x-javascript
                ;;
            *.css)
                t=text/css
                ;;
            *.html)
                t=text/html
                ;;
            *)
                t=`file -ib $f`
                ;;
        esac

        $e "$o$c-Type: $t\n$c-Length: `stat -c%s $f`"
        $e
        cat $f
        
    else
        $e "$h 404 Not Found\n"
    fi
    )'
done
