#!/bin/bash

proxy=127.0.0.1:9001

ii=x86
arch=$(uname -i)
case $arch in
    i686)
        ii=x86
        ;;
    *)
        ii=x86_64
        ;;
esac

cd $HOME
ALL_PROXY=socks5h://$proxy curl -L "https://www.dropbox.com/download?plat=lnx.$ii" -o dropbox.tar.gz

tar -xzf dropbox.tar.gz

~/.dropbox-dist/dropboxd
