#!/bin/sh

cd ~

dst="$HOME/SpiderOak Hive/vim"
[ -d "$dst" ] \
    && rsync -Rauv ~/bash.xp/vim.xp/./ \
    --delete \
    --exclude=.svn \
    --exclude=.git* \
    --exclude=*.pyc \
    --exclude=.Sync* \
    "$dst/./"
