#!/bin/sh

while read p pkg; do
    python3 -m venv $p
    if [ ".$pkg" = "." ]; then
        pkg=$p
    fi
    (
    cd $p
    source ./bin/activate
    pip3 install $pkg
    deactivate
    )
done <<-END
git GitPython
ipython
END
