set nocompatible
filetype plugin  on

let g:_tut_path = expand("<sfile>:h:h")
exe "set runtimepath+=" . g:_tut_path

set noswapfile
set list
set listchars=tab:].,trail:\|,extends:<,precedes:>
set number
