#!/bin/sh

. $HOME/bash.xp/script/rsyncbkp/sysconf

[ ! -f $bkpconf ] && { echo "no rsyncbkp conf found:$bkpconf">&2; exit 1; }
. $bkpconf



[ ! -d $bkpHome ] && { echo "bkpHome:$bkpHome does not exist">&2; exit 1; }
[ ! -d $bkpTargetDir ] && { echo "bkpTargetDir:$bkpTargetDir does not exist">&2; exit 1; }
bkpNamePre=${bkpNamePre-xpbkp}

date=`date "+%Y-%m-%dT%H_%M_%S"`
bkpTarget=$bkpTargetDir/$bkpNamePre-$date
bkpCurrent=$bkpTargetDir/current


echo "[INFO] backup from $bkpHome to $bkpTarget"

cd $bkpHome
cat $bkpfileFn | while read line; do
    rsync -azPRv \
        --delete \
        --delete-excluded \
        --filter=". $bkpfilterFn" \
        --link-dest="../current" \
        "$line" "$bkpTarget"
done

rm -f "$bkpCurrent" && ln -s "$bkpNamePre-$date" "$bkpCurrent"


# && ssh user@backupserver \
# "mv Backups/incomplete_back-$date Backups/back-$date \
